"""
Product Import Script - FIXED VERSION
Imports ALL 6,448 products from ITEMACTIVE CSV into SQL migration
"""
import pandas as pd
import os

# Configuration
CSV_PATH = r"c:\Users\laxmi\performance\app\data\ITEMACTIVE - Sheet 1.csv"
SQL_OUTPUT = r"c:\Users\laxmi\performance\app\supabase\migrations\021_import_products.sql"

def clean_string(s):
    """Clean string for SQL insertion"""
    if pd.isna(s):
        return None
    s = str(s).strip()
    s = s.replace("'", "''")  # Escape single quotes
    s = s.replace("\\", "")   # Remove backslashes
    return s if s else None

def generate_item_code(part_code, item_name, idx):
    """Generate unique item code"""
    if part_code:
        return clean_string(part_code)
    
    if item_name:
        # Extract first few chars of name
        prefix = ''.join(c for c in str(item_name)[:5] if c.isalnum()).upper()
        if prefix:
            return f"{prefix}{idx:05d}"
    
    return f"PROD{idx:06d}"

def normalize_uom(uom):
    """Normalize unit of measure"""
    if pd.isna(uom):
        return 'PCS'
    uom = str(uom).upper().strip()
    uom_map = {
        'PCS': 'PCS', 'NOS': 'PCS', 'PIECE': 'PCS',
        'KGS': 'KGS', 'KG': 'KGS', 'KILO': 'KGS',
        'ROLL': 'ROLL', 'ROLLS': 'ROLL',
        'SQM': 'SQM', 'MTR': 'MTR', 'LTR': 'LTR',
        'SET': 'SET', 'BOX': 'BOX', 'COILS': 'COILS'
    }
    return uom_map.get(uom, 'PCS')

def main():
    print("=" * 70)
    print("BENZ PACKAGING - FULL PRODUCT IMPORT")
    print("=" * 70)
    
    # Load CSV
    print("\n[1/4] Loading CSV...")
    df = pd.read_csv(CSV_PATH, encoding='utf-8', on_bad_lines='skip')
    print(f"   Loaded {len(df)} rows from CSV")
    
    # Prepare products
    print("\n[2/4] Processing products...")
    products = []
    seen_codes = set()
    seen_names = set()
    skipped_duplicates = 0
    skipped_empty = 0
    
    for idx, row in df.iterrows():
        # Get values
        item_code_raw = row.get('ITEMCODE')
        part_code = row.get('IT_PARTNO')
        item_name = row.get('IT_PARTNAME') or row.get('ITEMNAME')
        uom = row.get('UOM')
        
        # Clean values
        item_name_clean = clean_string(item_name)
        part_code_clean = clean_string(part_code)
        
        # Skip if no name
        if not item_name_clean:
            skipped_empty += 1
            continue
        
        # Generate unique item code
        item_code = generate_item_code(part_code_clean, item_name_clean, idx)
        
        # Handle duplicate codes
        original_code = item_code
        counter = 1
        while item_code in seen_codes:
            item_code = f"{original_code}_{counter}"
            counter += 1
        
        # Handle duplicate names - make unique by appending code
        original_name = item_name_clean
        if item_name_clean in seen_names:
            item_name_clean = f"{original_name} ({item_code})"
        
        # Skip if still duplicate
        if item_name_clean in seen_names:
            skipped_duplicates += 1
            continue
            
        seen_codes.add(item_code)
        seen_names.add(item_name_clean)
        
        products.append({
            'item_code': item_code,
            'item_name': item_name_clean,
            'uom': normalize_uom(uom),
            'part_code': part_code_clean
        })
    
    print(f"   Processed: {len(products)} products")
    print(f"   Skipped empty: {skipped_empty}")
    print(f"   Skipped duplicates: {skipped_duplicates}")
    
    # Generate SQL
    print("\n[3/4] Generating SQL...")
    
    with open(SQL_OUTPUT, 'w', encoding='utf-8') as f:
        f.write("-- =============================================================================\n")
        f.write("-- Auto-generated Product Import from ITEMACTIVE CSV\n")
        f.write(f"-- Total products: {len(products)}\n")
        f.write("-- Generated by: import_products.py\n")
        f.write("-- =============================================================================\n\n")
        
        # Add part_code column if not exists
        f.write("-- Ensure part_code column exists\n")
        f.write("DO $$ BEGIN\n")
        f.write("    IF NOT EXISTS (SELECT 1 FROM information_schema.columns\n")
        f.write("                   WHERE table_name = 'products' AND column_name = 'part_code') THEN\n")
        f.write("        ALTER TABLE products ADD COLUMN part_code VARCHAR(50);\n")
        f.write("    END IF;\n")
        f.write("END $$;\n\n")
        
        # Batch insert (100 products per INSERT for performance)
        batch_size = 100
        total_batches = (len(products) + batch_size - 1) // batch_size
        
        for batch_num in range(total_batches):
            start_idx = batch_num * batch_size
            end_idx = min(start_idx + batch_size, len(products))
            batch = products[start_idx:end_idx]
            
            f.write(f"-- Batch {batch_num + 1}/{total_batches} ({len(batch)} products)\n")
            f.write("INSERT INTO products (item_code, item_name, stock_uom, gst_rate, is_sales_item, maintain_stock, disabled, part_code) VALUES\n")
            
            values = []
            for p in batch:
                item_code = p['item_code']
                item_name = p['item_name']
                uom = p['uom']
                part_code = p['part_code'] or 'NULL'
                
                if part_code != 'NULL':
                    part_code = f"'{part_code}'"
                
                values.append(f"('{item_code}', '{item_name}', '{uom}', 18, true, true, false, {part_code})")
            
            f.write(',\n'.join(values))
            f.write("\nON CONFLICT (item_code) DO UPDATE SET item_name = EXCLUDED.item_name, stock_uom = EXCLUDED.stock_uom;\n\n")
    
    print(f"   Generated: {SQL_OUTPUT}")
    
    # Verify
    print("\n[4/4] Verifying...")
    file_size = os.path.getsize(SQL_OUTPUT)
    line_count = sum(1 for _ in open(SQL_OUTPUT, 'r', encoding='utf-8'))
    print(f"   File size: {file_size / 1024:.1f} KB")
    print(f"   Line count: {line_count}")
    
    print("\n" + "=" * 70)
    print(f"SUCCESS: {len(products)} products ready for import!")
    print("Run the SQL in Supabase Dashboard → SQL Editor")
    print("=" * 70)

if __name__ == "__main__":
    main()
