/**
 * Run migration 036 — push_subscriptions, notifications, task_comments
 */
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
let key = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
key = key.replace(/\\r\\n/g, '').replace(/"/g, '').trim();

const supabase = createClient(url, key);

const tables = [
    {
        name: 'push_subscriptions',
        sql: `CREATE TABLE IF NOT EXISTS push_subscriptions (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
      endpoint TEXT NOT NULL,
      p256dh TEXT NOT NULL,
      auth TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(user_id, endpoint)
    )`
    },
    {
        name: 'notifications',
        sql: `CREATE TABLE IF NOT EXISTS notifications (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
      task_id UUID REFERENCES tasks(id) ON DELETE SET NULL,
      type VARCHAR(50) DEFAULT 'task',
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      is_read BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`
    },
    {
        name: 'task_comments',
        sql: `CREATE TABLE IF NOT EXISTS task_comments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      author_id UUID NOT NULL REFERENCES profiles(user_id),
      body TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`
    }
];

async function run() {
    console.log('Running migration 036...');
    console.log('URL:', url);

    for (const table of tables) {
        console.log(`\nCreating ${table.name}...`);

        // Try inserting a test row to see if table exists
        const { error: checkError } = await supabase
            .from(table.name)
            .select('*')
            .limit(1);

        if (!checkError) {
            console.log(`  ✓ ${table.name} already exists`);
            continue;
        }

        // Table doesn't exist - we need to create it via SQL editor or REST
        console.log(`  Table ${table.name} does not exist yet. SQL:`);
        console.log(`  ${table.sql.replace(/\n/g, '\n  ')}`);
        console.log(`  → Run this SQL in Supabase Dashboard > SQL Editor`);
    }

    // Test access to existing tables
    const { data: existingTasks } = await supabase
        .from('tasks')
        .select('id')
        .limit(1);
    console.log('\n✓ Tasks table accessible, has data:', !!existingTasks?.length);

    console.log('\nDone! If tables need creating, run the SQL in Supabase Dashboard.');
}

run().catch(console.error);
