-- Auto-generated customer import from Party Master
-- Source: c:\Users\laxmi\performance\app\data\Commercial Master  dt. 22.08.2025 (1).xls

INSERT INTO customers (name, customer_code, created_at) VALUES
('AB PACKAGING SOLUTION', 'ABPA0001', NOW()),
('ADHESIVE SOLUTIONS', 'ADHES0002', NOW()),
('AEROL FORMULATIONS PVT. LTD.', 'AEROL0003', NOW()),
('A G PACKERS', 'AGP0004', NOW()),
('AG POLY PACKS PRIVATE LIMITED', 'AGPO0005', NOW()),
('AHM. MACHINES ( INDIA )', 'AHM0006', NOW()),
('Airtax Polymers Pvt.Ltd.', 'AIRTA0007', NOW()),
('Ajit Industries Pvt. Ltd.', 'AJIT0008', NOW()),
('AKAYGENTS PVT.LTD.', 'AKAYG0009', NOW()),
('A K INDUSTRIES', 'AKI0010', NOW()),
('ALLIANZ BUSINESS CORPORATION', 'ALLIA0011', NOW()),
('ALPNA TAPE INDUSTRIES & TRADING CO.', 'ALPNA0012', NOW()),
('AMAN DIE WORKS', 'AMAN0013', NOW()),
('AMG INDUSTRIES', 'AMGI0014', NOW()),
('Anant Industries', 'ANANT0015', NOW()),
('A-One Tex Tech Pvt. Ltd.', 'AONE0016', NOW()),
('ARAVALI FOAM PACKAGING', 'ARAVA0017', NOW()),
('Asht Vinayak Enterprises', 'ASHT0018', NOW()),
('A STAR PACKAGING', 'ASTA0019', NOW()),
('AVON CONTAINNERS PVT. LTD.', 'AVON0020', NOW()),
('AXSYS SOLUTIONS', 'AXSYS0021', NOW()),
('BABAJEE ENTERPRISES', 'BABAJ0022', NOW()),
('Bala Ji Store', 'BALA0023', NOW()),
('BALRAJ ENTERPRISES', 'BALRA0024', NOW()),
('BEE CHEMS', 'BEEC0025', NOW()),
('BEE CHEMS''''', 'BEEC0026', NOW()),
('BEHAL SONS', 'BEHAL0027', NOW()),
('BELLA VITA ORGANIC AND HERBAL SALON', 'BELLA0028', NOW()),
('BEST CONNECTION', 'BEST0029', NOW()),
('Bestoplast Industries ( P ) Ltd', 'BESTO0030', NOW()),
('BHAGWAN DASS AND SONS (INDIA) PVT LTD', 'BHAGW0031', NOW()),
('BHAGWATI PLYWOOD TRADERS', 'BHAGW0032', NOW()),
('Bharat Barrel & Drum Mfg Co.Pvt Ltd', 'BHARA0033', NOW()),
('BHARAT TRADERS', 'BHARA0034', NOW()),
('Bristol Industrial Electronics', 'BRIST0035', NOW()),
('CAPSTONE POLYWEAVE PVT.LTD.', 'CAPST0036', NOW()),
('CARETECH PACKAGING PVT.LTD.', 'CARET0037', NOW()),
('CENTURY DISTRIBUTORS PRIVATE LIMTED', 'CENTU0038', NOW()),
('Chanana Departmental Store', 'CHANA0039', NOW()),
('CHAWLA PLASTOPACK PRIVATE LIMITED', 'CHAWL0040', NOW()),
('Cimpress India Pvt.Ltd.', 'CIMPR0041', NOW()),
('CONCEPT PACKAGING', 'CONCE0042', NOW()),
('CORDIAL TECHNOLOGIES PVT.LTD.', 'CORDI0043', NOW()),
('Crimson Communicare LLP', 'CRIMS0044', NOW()),
('Dascan Enterprises', 'DASCA0045', NOW()),
('Dashmesh Plastic', 'DASHM0046', NOW()),
('DAWER PROPACK PRIVATE LIMITED', 'DAWER0047', NOW()),
('DDL INDUSTRIES', 'DDLI0048', NOW()),
('DIPLOMAT DRAWING EMPORIUM', 'DIPLO0049', NOW()),
('D-PACK SOLUTIONS', 'DPAC0050', NOW()),
('DREAMS THE FURNISHING GALLERY PVT.LTD.', 'DREAM0051', NOW()),
('DURAPAK', 'DURAP0052', NOW()),
('DURGA CHEMICALS', 'DURGA0053', NOW()),
('DVM INDUSTRIES', 'DVMI0054', NOW()),
('DYNAMIC SALES CORPORATION', 'DYNAM0055', NOW()),
('EEWA ENGINEERING CO. PVT. LTD.', 'EEWA0056', NOW()),
('Electro Sales Corporation', 'ELECT0057', NOW()),
('EMPERIAL STRETCH LLP', 'EMPER0058', NOW()),
('ESSENCE TAPE INTERNATIONAL PVT. LTD.', 'ESSEN0059', NOW()),
('FELT HOUSE', 'FELT0060', NOW()),
('Ferreterro India Pvt. Ltd.', 'FERRE0061', NOW()),
('FLEXIFOIL PACKAGING PRIVATE LIMITED', 'FLEXI0062', NOW()),
('Fortune Stretch Pack', 'FORTU0063', NOW()),
('FUTURISTIC MARKETING SOLUTION', 'FUTUR0064', NOW()),
('GHANSHAM ICE BOX MANFRS. (REGD.)', 'GHANS0065', NOW()),
('Goel Emporium', 'GOEL0066', NOW()),
('GOVARDHAN SAW MILL&TIMBER DEPOT', 'GOVAR0067', NOW()),
('GOYAL PLYWOOD LLP', 'GOYAL0068', NOW()),
('GREEN PACK INDIA', 'GREEN0069', NOW()),
('GRV INTERNATIONAL', 'GRVI0070', NOW()),
('G R Virindera Industries', 'GRV0071', NOW()),
('GUNJAN TIMBER', 'GUNJA0072', NOW()),
('Gupta Canvas', 'GUPTA0073', NOW()),
('Guruji Trading Company', 'GURUJ0074', NOW()),
('GURU NANAK CANVAS STORE', 'GURU0075', NOW()),
('HARISH ELECTRICALS', 'HARIS0076', NOW()),
('H.K.S INTERNATIONAL', 'HKS0077', NOW()),
('Honeyshield Emballeurs', 'HONEY0078', NOW()),
('Hydro Pneumatics & Spares', 'HYDRO0079', NOW()),
('IDAM NATURAL WELLNESS PRIVATE LIMITED', 'IDAM0080', NOW()),
('Ideal Packaging', 'IDEAL0081', NOW()),
('Industrial Tapes & Packers', 'INDUS0082', NOW()),
('JAGDISH SALES', 'JAGDI0083', NOW()),
('JAI BHARAT ENGINEERING WORKS', 'JAIB0084', NOW()),
('Jai Narayan Enterprises', 'JAIN0085', NOW()),
('JAIN TEX NON WOVEN PVT. LTD. ( Ghaziabad )', 'JAIN0086', NOW()),
('JAIN TEX NONWOVENS PRIVATE LIMITED', 'JAIN0087', NOW()),
('JAI SHREE INTERNATIONAL', 'JAIS0088', NOW()),
('Jawala Parshad and Co. Pvt. Ltd.', 'JAWAL0089', NOW()),
('JAWALA PARSHAD & CO.', 'JAWAL0090', NOW()),
('Jeet Industries', 'JEET0091', NOW()),
('Jhalani Trade Centre', 'JHALA0092', NOW()),
('JINDAL PAPER PRODUCTS', 'JINDA0093', NOW()),
('J J PLASTALLOY PRIVATE LIMITED', 'JJP0094', NOW()),
('J.J. PLASTALLOY PVT. LTD.', 'JJ0095', NOW()),
('J.K.Sales Corporation', 'JKS0096', NOW()),
('Johri Mal Gauri Shankar', 'JOHRI0097', NOW()),
('JSKM ENTERPRISES INDIA PVT. LTD.', 'JSKM0098', NOW()),
('J V & COMPANY', 'JV0099', NOW()),
('KAMSID INDIA', 'KAMSI0100', NOW()),
('KARAM PET STRAP INDUSTRIES', 'KARAM0101', NOW()),
('KHUSHI TRADERS', 'KHUSH0102', NOW()),
('KIRAN ENTERPRISES', 'KIRAN0103', NOW()),
('KOHLI ENGRAVURE (INDIA)', 'KOHLI0104', NOW()),
('KONTINER INDIA PRIVATE LIMITED', 'KONTI0105', NOW()),
('Krishna International', 'KRISH0106', NOW()),
('KRISHNA OVERSEAS INTERNATIONAL', 'KRISH0107', NOW()),
('Kronosco Indventures Pvt.Ltd.', 'KRONO0108', NOW()),
('LAXMI INDUSTRIAL PRODUCTS', 'LAXMI0109', NOW()),
('LINK AGENCIES', 'LINK0110', NOW()),
('L K ENTERPRISES', 'LKE0111', NOW()),
('Lotus Shielders ( India ) Pvt.Ltd.', 'LOTUS0112', NOW()),
('Maharashtra Plastic & Industries', 'MAHAR0113', NOW()),
('Malansh International', 'MALAN0114', NOW()),
('MALIK AND SONS', 'MALIK0115', NOW()),
('MANVI PLAST INDIA PRIVATE LIMITED', 'MANVI0116', NOW()),
('Marathe Infotech Pvt.Ltd.', 'MARAT0117', NOW()),
('Mars Packaging (P) Ltd.( Unit - 11 )', 'MARS0118', NOW()),
('MAXBROS VENTURES INDIA LIMITED', 'MAXBR0119', NOW()),
('M C MACHINERY CENTRE', 'MCM0120', NOW()),
('M & H Packtech', 'MH0121', NOW()),
('Mico Plast Industries Pvt.Ltd.', 'MICO0122', NOW()),
('M.K. BIRD NETS SERVICES', 'MK0123', NOW()),
('M.K.G. HYDRO PNEUTECH SYSTEM', 'MKG0124', NOW()),
('M.L.M.INDIA LIMITED', 'MLM0125', NOW()),
('MODERN INDIAN TRADING', 'MODER0126', NOW()),
('Mondal Brothers', 'MONDA0127', NOW()),
('MORYA PACKAGING', 'MORYA0128', NOW()),
('M.R.Paper Traders', 'MRP0129', NOW()),
('MSG KITCHENS', 'MSGK0130', NOW()),
('M/s VIJAY KUMAR JAIN', 'MSV0131', NOW()),
('NATRAJ DRUM INDUSTRIES PVT. LTD.', 'NATRA0132', NOW()),
('Neelam Consultant & Traders', 'NEELA0133', NOW()),
('NEWAGE LAMINATORS PRIVATE LIMITED', 'NEWAG0134', NOW()),
('NEWGEN SECIALTY PLASTICS LTD', 'NEWGE0135', NOW()),
('New Light Products', 'NEWL0136', NOW()),
('New Sales Corporation', 'NEWS0137', NOW()),
('Nickron Packaging', 'NICKR0138', NOW()),
('NITI PLASTIC INDUSTRIES', 'NITI0139', NOW()),
('OM CANVAS UDYOG', 'OMCA0140', NOW()),
('ONLY SHYAM POLYMER', 'ONLY0141', NOW()),
('OPULENT LIVING INC.', 'OPULE0142', NOW()),
('Packraft Container India (P) Ltd', 'PACKR0143', NOW()),
('Pal Hardware & Electric Store', 'PALH0144', NOW()),
('PANAMAX LIMITED', 'PANAM0145', NOW()),
('Panamax Tapes International', 'PANAM0146', NOW()),
('PARAMOUNT FOAMS PRIVATE LIMITED', 'PARAM0147', NOW()),
('PARAMOUNT INTERCONTINENTAL PVT LTD', 'PARAM0148', NOW()),
('Paramount Iron & Steel Works (P) Ltd', 'PARAM0149', NOW()),
('Parushni Interior Designs Private Limited', 'PARUS0150', NOW()),
('Pawan Doot Industries', 'PAWAN0151', NOW()),
('PEPEJOHNS APPARELS LLP', 'PEPEJ0152', NOW()),
('PIONEER ENTERPRISES (INDIA ) PRIVATE LIMITED', 'PIONE0153', NOW()),
('Placero International', 'PLACE0154', NOW()),
('Plasmix Private limited', 'PLASM0155', NOW()),
('PLASTIC PACKING HOUSE', 'PLAST0156', NOW()),
('PON PURE CHEMICAL INDIA PRIVATE LIMITED', 'PONP0157', NOW()),
('Pon Pure Chemical India Pvt.Ltd', 'PONP0158', NOW()),
('PRAKRITI INDUSTRIES ( Purchase )', 'PRAKR0159', NOW()),
('PRATHAM POLY PLAST', 'PRATH0160', NOW()),
('PRIYA PACKAGING', 'PRIYA0161', NOW()),
('Priya Packaging Unit - 11', 'PRIYA0162', NOW()),
('PUNJ PACKAGING INDUSTRIES', 'PUNJ0163', NOW()),
('PYRAMID PLY AND WOOD PRODUCTS PVT.LTD.', 'PYRAM0164', NOW()),
('QUEBEC PETROLEUM RESOURCES LTD.', 'QUEBE0165', NOW()),
('Raajratna Ventures Ltd', 'RAAJR0166', NOW()),
('Rahul Timber Traders', 'RAHUL0167', NOW()),
('RAMBHA DRESSES', 'RAMBH0168', NOW()),
('RAM PACKAGING SOLUTIONS', 'RAMP0169', NOW()),
('R A NARIMAN & CO. PVT LTD.', 'RAN0170', NOW()),
('RATTAN LAL JAIN &  BROS.', 'RATTA0171', NOW()),
('RAVI METAL HOUSE', 'RAVI0172', NOW()),
('R B PLASTIC', 'RBP0173', NOW()),
('RBP SOLUTIONS PRIVATE LIMITED', 'RBPS0174', NOW()),
('REDCLIFFE HYGIENE PRIVATE LIMITED', 'REDCL0175', NOW()),
('REGAL ECO PACK', 'REGAL0176', NOW()),
('REPOOL INDIA', 'REPOO0177', NOW()),
('RESEARCH AND DEVLOPMENT PACKAGING', 'RESEA0178', NOW()),
('Riddhi Siddhi Packagng Solutions', 'RIDDH0179', NOW()),
('RIDLEY LIFE SCIENCE PRIVATE LIMITED', 'RIDLE0180', NOW()),
('R K Beri & Sons', 'RKB0181', NOW()),
('R.K. PAPER TRADERS', 'RK0182', NOW()),
('R K POLY ADDITIVES', 'RKP0183', NOW()),
('ROBOTEK LLP', 'ROBOT0184', NOW()),
('Roto India', 'ROTO0185', NOW()),
('Royal Timber Store', 'ROYAL0186', NOW()),
('R.S. PACKAGING', 'RS0187', NOW()),
('R S Polyfilms', 'RSP0188', NOW()),
('R S POLYFILMS ( Sonipat )', 'RSP0189', NOW()),
('SABENA ENTERPRISES', 'SABEN0190', NOW()),
('Sai Packaging  (P)', 'SAIP0191', NOW()),
('SARUP SINGH ADARSH PAL SINGH', 'SARUP0192', NOW()),
('SCG & Compnay', 'SCG0193', NOW()),
('S D POLYFILMS', 'SDP0194', NOW()),
('S D POLYFILMS PRIVATE LIMITED', 'SDP0195', NOW()),
('SERWIN PHARMACEUTICALS', 'SERWI0196', NOW()),
('SGS FABRICATION WORKS', 'SGSF0197', NOW()),
('SHIVAM AGENCIES', 'SHIVA0198', NOW()),
('Shivam H/W Paints & Electrical Store', 'SHIVA0199', NOW()),
('SHREE BALAJI ENTERPRISES', 'SHREE0200', NOW()),
('SHREE DEV PLYWOOD & TIMBER', 'SHREE0201', NOW()),
('SHREEJEE TRADING CO.', 'SHREE0202', NOW()),
('SHREE PAPER MART', 'SHREE0203', NOW()),
('SHREE RAM INDUSTRIES', 'SHREE0204', NOW()),
('SHREE RAM PACKAGING INDUSTRIES', 'SHREE0205', NOW()),
('Shree Salasar Timber & Plywood', 'SHREE0206', NOW()),
('Shri Ram Packaging Industries', 'SHRI0207', NOW()),
('Shri Ram Packaging Industries ( Unit -11)', 'SHRI0208', NOW()),
('Shyam Flexi Pack Industries', 'SHYAM0209', NOW()),
('Siddharth Plywood', 'SIDDH0210', NOW()),
('SIGNODE INDIA LTD.', 'SIGNO0211', NOW()),
('S.K.PACKAGING', 'SKP0212', NOW()),
('Skypac Plastica', 'SKYPA0213', NOW()),
('SL INTERIOR LLP', 'SLIN0214', NOW()),
('Sonia Novelties', 'SONIA0215', NOW()),
('SOUTH INDIA POLYPRO PVT.LTD.', 'SOUTH0216', NOW()),
('Spinefit Medical Pvt.Ltd.', 'SPINE0217', NOW()),
('SRI SAI TRADING CO. (P)', 'SRIS0218', NOW()),
('SRPI INDIA', 'SRPI0219', NOW()),
('SRV Damage Preventions Pvt.Ltd.', 'SRVD0220', NOW()),
('STALLION PACKAGING PVT.LT.D', 'STALL0221', NOW()),
('Standard Packaging', 'STAND0222', NOW()),
('Steel Barrel Pvt.Ltd.', 'STEEL0223', NOW()),
('Storopack India Private Limited', 'STORO0224', NOW()),
('Strips India', 'STRIP0225', NOW()),
('STRIPS INDIA TECHNOVATIONS PRIVATE LIMITED', 'STRIP0226', NOW()),
('SUNARIYA ENTERPRISES', 'SUNAR0227', NOW()),
('Sun Pack India Industries', 'SUNP0228', NOW()),
('SUPREME INDUSTRIES', 'SUPRE0229', NOW()),
('SURYA KIRAN METALS PVT.LTD.', 'SURYA0230', NOW()),
('S.V. POLYMERS', 'SV0231', NOW()),
('SWASTIK CHEMICALS', 'SWAST0232', NOW()),
('Swastik Industries International Pvt. Ltd.', 'SWAST0233', NOW()),
('TANIA POLY FILMS PRIVATE LIMITED', 'TANIA0234', NOW()),
('TECHNOPEX POLYMERS', 'TECHN0235', NOW()),
('Techno RTM India', 'TECHN0236', NOW()),
('THE EXCELLENCE STORE', 'THEE0237', NOW()),
('The Supreme Industries Ltd', 'THES0238', NOW()),
('The Supreme Industries Ltd ( Manesar )', 'THES0239', NOW()),
('Transpack', 'TRANS0240', NOW()),
('Transport Packaging Solution', 'TRANS0241', NOW()),
('T.R. Packaging', 'TR0242', NOW()),
('Ultimate Flexipack Ltd', 'ULTIM0243', NOW()),
('Unitech Industrial Solutions (P)', 'UNITE0244', NOW()),
('UNIVERSAL EYE GLASSES', 'UNIVE0245', NOW()),
('Valvoline Cummins Private Limited', 'VALVO0246', NOW()),
('VALVOLINE CUMMINS PVT. LTD. ( Maharashtra )', 'VALVO0247', NOW()),
('VARDHMAN PLASTICS', 'VARDH0248', NOW()),
('VIBGYOR INDUSTRIAL ENTERPRISES', 'VIBGY0249', NOW()),
('VIKAS TRADERS CO.', 'VIKAS0250', NOW()),
('VINAYAK UDYOG', 'VINAY0251', NOW()),
('V.R.Enterprises', 'VRE0252', NOW()),
('Wellpack Industries', 'WELLP0253', NOW()),
('YANA PACKAGING SOLUTIONS', 'YANA0254', NOW()),
('YASHVIN ENTERPRISES', 'YASHV0255', NOW()),
('Yoghem Packaging Inida Pvt.Ltd.', 'YOGHE0256', NOW()),
('2 Friends Tempo Service', '2FRI0257', NOW()),
('3 Multitech Systems', '3MUL0258', NOW()),
('3S Solutions.in', '3SSO0259', NOW()),
('7 Amaze', '7AMA0260', NOW()),
('Aaram Polyfoam LLP', 'AARAM0261', NOW()),
('Aarav Pest Management', 'AARAV0262', NOW()),
('AAR GEE INTERNATIONAL', 'AARG0263', NOW()),
('ABHISHAKE KULDEEP AND CO', 'ABHIS0264', NOW()),
('Abhishekh Cargo Movers', 'ABHIS0265', NOW()),
('ACCURATE FREIHT CARRIERS PRIVATE LIMITED', 'ACCUR0266', NOW()),
('Accurax Solution', 'ACCUR0267', NOW()),
('ACE SECURITY SOLUTIONS', 'ACES0268', NOW()),
('ADITYA TEMPO & LOGISTIC', 'ADITY0269', NOW()),
('Admire Consultant & Safety Services', 'ADMIR0270', NOW()),
('Adroit Logistic ( Landlord )', 'ADROI0271', NOW()),
('ADROIT LOGISTICS', 'ADROI0272', NOW()),
('Adroit Logistics ( Old )', 'ADROI0273', NOW()),
('Adroit Logisttics ( MP )', 'ADROI0274', NOW()),
('ADROIT LOGITICS ( PUNE )', 'ADROI0275', NOW()),
('ADROIT SUPPLY CHAIN MANAGEMENT PRIVATE LIMITED', 'ADROI0276', NOW()),
('ADROIT SUPPLY CHAIN MANAGEMTN (P) Ltd. (M)', 'ADROI0277', NOW()),
('AES LABORATORIES PRIVATE LIMITED', 'AESL0278', NOW()),
('AFFINITY LOGISTICS & PLANNERS PVT.LTD.', 'AFFIN0279', NOW()),
('Ahirwal Trading & Mill Store -Manesar', 'AHIRW0280', NOW()),
('Air Asia ( India ) Ltd', 'AIRA0281', NOW()),
('Air France', 'AIRF0282', NOW()),
('Air India Ltd', 'AIRI0283', NOW()),
('Airline Allied Service Limited', 'AIRLI0284', NOW()),
('Airtel Relationship No - 1166968140', 'AIRTE0285', NOW()),
('Airtel Relationship No.7005564969', 'AIRTE0286', NOW()),
('Airtel Relationship No.7005564970', 'AIRTE0287', NOW()),
('Airtel Relationship No.7033861059', 'AIRTE0288', NOW()),
('Air World Express', 'AIRW0289', NOW()),
('AJIT KUMAR', 'AJIT0290', NOW()),
('Ajmer Singh', 'AJMER0291', NOW()),
('AKD Hygiene Solutions', 'AKDH0292', NOW()),
('Ak Transport', 'AKTR0293', NOW()),
('Alka Lifestyles Pvt.Ltd.', 'ALKA0294', NOW()),
('Allied Protection Assurance Company', 'ALLIE0295', NOW()),
('All Maintenance India', 'ALLM0296', NOW()),
('Alpinesoft IT Solutions Pvt.LTd.', 'ALPIN0297', NOW()),
('AMAZON INTERNET SERVICES PRIVATE LIMITED', 'AMAZO0298', NOW()),
('Anand Agencys', 'ANAND0299', NOW()),
('Anand Bajpai', 'ANAND0300', NOW()),
('Anand Raj Associate', 'ANAND0301', NOW()),
('Anchor Logistics', 'ANCHO0302', NOW()),
('ANITA DIARIES', 'ANITA0303', NOW()),
('A - One Music & Computers', 'AO0304', NOW()),
('Apagen Solutions Pvt. Ltd.', 'APAGE0305', NOW()),
('Apex Systems', 'APEX0306', NOW()),
('APPARIO RETAIL PRIVATE LIMITED', 'APPAR0307', NOW()),
('Applore Technologies Pvt Ltd', 'APPLO0308', NOW()),
('ARAMEX INDIA PVT.LTD.', 'ARAME0309', NOW()),
('ARC Dezine', 'ARCD0310', NOW()),
('Armaan Battery', 'ARMAA0311', NOW()),
('ARNEJA MACHINERY & EXPORT HOUSE', 'ARNEJ0312', NOW()),
('ARUN TRANSPORT CARRIER', 'ARUN0313', NOW()),
('Aryavart Motor Transport Co.', 'ARYAV0314', NOW()),
('AS Consultants', 'ASCO0315', NOW()),
('Ashok', 'ASHOK0316', NOW()),
('Asian Hobby Crafts LLP', 'ASIAN0317', NOW()),
('Associated Road Carriers Ltd', 'ASSOC0318', NOW()),
('Atharva Laboratories Pvt. Ltd.', 'ATHAR0319', NOW()),
('Avtar Singh Bedi & Inderjeet Kaur', 'AVTAR0320', NOW()),
('BABA AUTO WORKS', 'BABA0321', NOW()),
('Baba Goods Carriers', 'BABA0322', NOW()),
('Bagga Traders', 'BAGGA0323', NOW()),
('Bala Ji Cargo Moving Transport', 'BALA0324', NOW()),
('Bala Ji Courier Express', 'BALA0325', NOW()),
('BALTIC LEI INDIA PRIVATE LIMITED', 'BALTI0326', NOW()),
('BALWAN SINGH TRANSPORT WORKS', 'BALWA0327', NOW()),
('Balwant printers pvt.ltd.', 'BALWA0328', NOW()),
('B Chandra  and Associate', 'BCHA0329', NOW()),
('Beli Ram Tara Chand Jain', 'BELI0330', NOW()),
('Bhagat Ram', 'BHAGA0331', NOW()),
('BHALLA BATTERY HOUSE', 'BHALL0332', NOW()),
('Bharti Airtel Ltd', 'BHART0333', NOW()),
('Bhola Transport Company', 'BHOLA0334', NOW()),
('BIZ PRINT MEDIA TECHNOLOGIES PRIVATE LIMITED', 'BIZP0335', NOW()),
('BLUE BIRD PEST CONTROL PRIVATE LIMITED', 'BLUE0336', NOW()),
('BLUE DART EXPRESS LTD .', 'BLUE0337', NOW()),
('BRISTOL ELECTRICALS', 'BRIST0338', NOW()),
('B & R Transport Corporation', 'BR0339', NOW()),
('Brunel Logistic India Pvt. Ltd.', 'BRUNE0340', NOW()),
('BUDGET COURIERS PVT LTD', 'BUDGE0341', NOW()),
('Budgetpe Private Limited', 'BUDGE0342', NOW()),
('Capital Vehicles Sales Ltd', 'CAPIT0343', NOW()),
('Care Health Insurance Ltd', 'CARE0344', NOW()),
('Carewell Cargo Movers ( P ) Ltd.', 'CAREW0345', NOW()),
('Cargo Motors (Kutch) Pvt.Ltd.', 'CARGO0346', NOW()),
('Cartfire India', 'CARTF0347', NOW()),
('Cathay Pacific Airways Ltd', 'CATHA0348', NOW()),
('CELEBI DELHI CARGO TERMINAL MANAGEMENT INDIA P LTD.', 'CELEB0349', NOW()),
('Chaitanya Chopra ( Expenses A/c )', 'CHAIT0350', NOW()),
('Chand Company', 'CHAND0351', NOW()),
('Charu Motors Pvt.Ltd.', 'CHARU0352', NOW()),
('Chuhra Ram', 'CHUHR0353', NOW()),
('CLASSIC DIARY HOUSE', 'CLASS0354', NOW()),
('Clearport Cargo Solutions Pvt. Ltd.', 'CLEAR0355', NOW()),
('Cleartrip Private Ltd', 'CLEAR0356', NOW()),
('CLOUDTAIL INDIA PRIVATE LIMITED', 'CLOUD0357', NOW()),
('CMA CGM Agencies India Pvt.Ltd.', 'CMAC0358', NOW()),
('Coffee Day Global Ltd', 'COFFE0359', NOW()),
('COMPETENT LIFTERS', 'COMPE0360', NOW()),
('Confederation of Indian Industry', 'CONFE0361', NOW()),
('Console Shipping Services India Pvt.Ltd.', 'CONSO0362', NOW()),
('Container Corporation of India Ltd', 'CONTA0363', NOW()),
('Corpseed Ites Private Limited', 'CORPS0364', NOW()),
('Countwell Data Processing', 'COUNT0365', NOW()),
('Dalip Chand S/o Kishan', 'DALIP0366', NOW()),
('DARSHAN SINGH', 'DARSH0367', NOW()),
('DAVINDER CHUGH', 'DAVIN0368', NOW()),
('De''Com Systems', 'DEC0369', NOW()),
('DECOM SYSTEMS', 'DECOM0370', NOW()),
('Deepak Bhardwaj', 'DEEPA0371', NOW()),
('DEEYA PANEL PRODUCTS PRIVATE LIMITED', 'DEEYA0372', NOW()),
('DEFY MOTORS PVT.LTD.', 'DEFY0373', NOW()),
('DELHI GRAVURES CYLINDER', 'DELHI0374', NOW()),
('Delhi Modi Express Transport Co.', 'DELHI0375', NOW()),
('DELHI MODI TRANSPORT CO.', 'DELHI0376', NOW()),
('Delhi Rajasthan Transport Co.Ltd', 'DELHI0377', NOW()),
('Delhi Rishikesh Transport Service', 'DELHI0378', NOW()),
('Delight Xpress', 'DELIG0379', NOW()),
('Dena Industries', 'DENA0380', NOW()),
('DEVANSH TRANSPORT SERVICES', 'DEVAN0381', NOW()),
('DG Event', 'DGEV0382', NOW()),
('Dhl Express India Pvt.Ltd.', 'DHLE0383', NOW()),
('Digigen Technology Pvt.Ltd.', 'DIGIG0384', NOW()),
('Divine Infotech Solutions', 'DIVIN0385', NOW()),
('Divya Laxmi Overseas', 'DIVYA0386', NOW()),
('DJ Hospitality', 'DJHO0387', NOW()),
('DSS GROUP', 'DSSG0388', NOW()),
('DTDC Express Ltd', 'DTDC0389', NOW()),
('Dun & Bradstreet Information Service', 'DUN0390', NOW()),
('DYNAMIC ENGINEERS AND ELECTROPLATERS', 'DYNAM0391', NOW()),
('EASY CARRY TECHNOLOGIES INDIA PVT LTD', 'EASY0392', NOW()),
('Easy Trip Planners Ltd', 'EASY0393', NOW()),
('Eco Beverages', 'ECOB0394', NOW()),
('Egotude India', 'EGOTU0395', NOW()),
('Emirates', 'EMIRA0396', NOW()),
('Emirates Shipping Agencies ( India ) Pvt.Ltd.', 'EMIRA0397', NOW()),
('EMPIRE TUBEWELLS PVT.LTD.', 'EMPIR0398', NOW()),
('ENCORE MODULAR FURNITURE PVT.LTD.', 'ENCOR0399', NOW()),
('EVEREST LOGISTICS', 'EVERE0400', NOW()),
('Evergreen Testing Co.', 'EVERG0401', NOW()),
('EXAINFOTECH (I) PVT. LTD.', 'EXAIN0402', NOW()),
('Excella Co Working Space', 'EXCEL0403', NOW()),
('EXIM PLANNERS AND TRAVELS', 'EXIM0404', NOW()),
('Express Cargo Containers', 'EXPRE0405', NOW()),
('FAR EASTERN ROADWAYS', 'FARE0406', NOW()),
('FASHNEAR TECHNOLOGIES PRIVATE LIMITED', 'FASHN0407', NOW()),
('FEDEX EXPRESS TRANSPORTATION AND SUPPLY CHAIN SERVICES (I) Pvt.Ltd.', 'FEDEX0408', NOW()),
('FedEx India Pvt.Ltd.', 'FEDEX0409', NOW()),
('Flixtel Communication Pvt.Ltd.', 'FLIXT0410', NOW()),
('FlySquare Solution', 'FLYSQ0411', NOW()),
('FSR Travels Pvt.Ltd.', 'FSRT0412', NOW()),
('Future Generali India Insurance Co.Ltd.', 'FUTUR0413', NOW()),
('Galaxy Texfab LlP', 'GALAX0414', NOW()),
('GANGADHAR KUMAR DEVARAKONDA', 'GANGA0415', NOW()),
('GATI-KINTETSU EXPRESS PVT.LTD.', 'GATI0416', NOW()),
('Gaurav Electromech', 'GAURA0417', NOW()),
('G.Enviro Solutions', 'GENV0418', NOW()),
('Ghan Shyam Transport', 'GHAN0419', NOW()),
('GIANENDER AND ASSOCIATES', 'GIANE0420', NOW()),
('Global Cargo Services Pvt. Ltd.', 'GLOBA0421', NOW()),
('Global Enviro Solutions', 'GLOBA0422', NOW()),
('GLOBAL VISION LAW FIRM', 'GLOBA0423', NOW()),
('GLOBELINK WW INDIA PVT.LTD.', 'GLOBE0424', NOW()),
('Globestar Groupage Services Pvt. Ltd.', 'GLOBE0425', NOW()),
('Go Airlines India Ltd', 'GOAI0426', NOW()),
('Gondals Press India Ltd.', 'GONDA0427', NOW()),
('Goofy Tails Private Limited', 'GOOFY0428', NOW()),
('Gopal Chauhan', 'GOPAL0429', NOW()),
('GOVIND SOFT TECHNOLOGY', 'GOVIN0430', NOW()),
('Green Lab Analysis And Research Centre Pvt.Ltd.', 'GREEN0431', NOW()),
('GROZNET INDUSTRIES', 'GROZN0432', NOW()),
('Gseven Computer Business Pvt.Ltd.', 'GSEVE0433', NOW()),
('GUARANTORS INFRASTRUCTURE PRIVATE LIMITED', 'GUARA0434', NOW()),
('Gupta H/W Paints & Electricals', 'GUPTA0435', NOW()),
('GVS INTERNATIONAL', 'GVSI0436', NOW()),
('HIND TRANSPORT SERVICES', 'HIND0437', NOW()),
('Hindustan Steel Trading', 'HINDU0438', NOW()),
('HITANKSHA JAIN', 'HITAN0439', NOW()),
('HITECH MACHINERIES & EQUIPMENTS', 'HITEC0440', NOW()),
('HMS Group', 'HMSG0441', NOW()),
('HRIDAYA AGENCIES', 'HRIDA0442', NOW()),
('HSIIDC', 'HSIID0443', NOW()),
('IAL LOGISTICS INDIA LTD.', 'IALL0444', NOW()),
('ICICI LOMBARD GENERAL INSURANCE CO.LTD.', 'ICICI0445', NOW()),
('Iffco Tokiyo Ltd', 'IFFCO0446', NOW()),
('IG HOSPITALITY', 'IGHO0447', NOW()),
('India Institute of Packaging', 'INDIA0448', NOW()),
('Indiamart Intermesh Limited', 'INDIA0449', NOW()),
('Indian Institute of Packaging', 'INDIA0450', NOW()),
('INDIAN RAIL CARGO SERVICE', 'INDIA0451', NOW()),
('INDO ARYA CENTRAL TRANSPORT LTD.', 'INDO0452', NOW()),
('Indusage Techapp Private Limited', 'INDUS0453', NOW()),
('I Need Trip  Solutions', 'INEE0454', NOW()),
('I Need Trip Travels (P) Ltd.', 'INEE0455', NOW()),
('INEXT GLOBAL LOGISTICS  SOLUTIONS PVT.LTD.', 'INEXT0456', NOW()),
('INEXT LOGISTICS AND SUPPLY CHAIN PVT LTD', 'INEXT0457', NOW()),
('Info Edge India Ltd', 'INFO0458', NOW()),
('INLAND WORLD LOGISTICS PVT.LTD.', 'INLAN0459', NOW()),
('INTERGLOBE AVIATION LTD', 'INTER0460', NOW()),
('INTERTEK INDIA PRIVATE LIMITED', 'INTER0461', NOW()),
('INXPRESS INDIA PRIVATE LIMITED', 'INXPR0462', NOW()),
('Inxpress India Pvt.Ltd.', 'INXPR0463', NOW()),
('ITS TECHNOLOGIES', 'ITST0464', NOW()),
('Jaguar Solutions Pvt.Ltd.', 'JAGUA0465', NOW()),
('Jai Durga Body Works', 'JAID0466', NOW()),
('Jaipur Golden Transport Co. Pvt. Ltd.', 'JAIPU0467', NOW()),
('JANVI LOGISTICS', 'JANVI0468', NOW()),
('JAY MAA MANSHA TRANSPORT', 'JAYM0469', NOW()),
('Jeet Pal', 'JEET0470', NOW()),
('JET AIRWAYS INDIA LTD', 'JETA0471', NOW()),
('JMD HOLIDAYS', 'JMDH0472', NOW()),
('JMD TRADERS', 'JMDT0473', NOW()),
('J M K LOGISTICS', 'JMK0474', NOW()),
('J.N. Yadav Transport', 'JN0475', NOW()),
('Jyoti Enterprises', 'JYOTI0476', NOW()),
('Kaira District Co - Operative Milk Producers Union', 'KAIRA0477', NOW()),
('KAIZEN SOLUTIONS', 'KAIZE0478', NOW()),
('Kallal Ecommerce Global (OPC) Pvt.Ltd.', 'KALLA0479', NOW()),
('Kallal Ecommerce Global Trade ( OPC ) Pvt. Ltd.', 'KALLA0480', NOW()),
('Kamal Tools', 'KAMAL0481', NOW()),
('Karamvir', 'KARAM0482', NOW()),
('Kedia Enterprises', 'KEDIA0483', NOW()),
('Khandelwal Sales Corporation', 'KHAND0484', NOW()),
('KHANNA CARGO CARRIERS', 'KHANN0485', NOW()),
('Khanna Trading Company', 'KHANN0486', NOW()),
('KIDAO LABORATORIES', 'KIDAO0487', NOW()),
('Konnection India Dot Com Private Limited.', 'KONNE0488', NOW()),
('K P Tender Advisor Private Limited', 'KPT0489', NOW()),
('Krishan Kumar So Chetram', 'KRISH0490', NOW()),
('Kritivaas Freight Movers Pvt,Ltd', 'KRITI0491', NOW()),
('K.T.S. Tempo Service', 'KTS0492', NOW()),
('Kuldeep Tempo Service', 'KULDE0493', NOW()),
('Kunal Motors', 'KUNAL0494', NOW()),
('KUNAL STATIONERY MART', 'KUNAL0495', NOW()),
('Kundan Electronics', 'KUNDA0496', NOW()),
('KUNDRA MEDIA & COMPANY', 'KUNDR0497', NOW()),
('LABHUB GLOBAL LLP', 'LABHU0498', NOW()),
('LAKSHAY BODY WORKS', 'LAKSH0499', NOW()),
('Landmark lifestyle cars Pvt. Ltd.', 'LANDM0500', NOW()),
('LCI Engineering India Pvt.Ltd.', 'LCIE0501', NOW()),
('Liberty General Insurance Ltd', 'LIBER0502', NOW()),
('Link Logistics Management Pvt.Ltd.', 'LINK0503', NOW()),
('Looms & Weaves', 'LOOMS0504', NOW()),
('Lotus International Logitics', 'LOTUS0505', NOW()),
('MAC Lifestyle Products Ltd.', 'MACL0506', NOW()),
('Mahalakshmi Logistics Pvt.Ltd.', 'MAHAL0507', NOW()),
('Mahesh Sharma Motors', 'MAHES0508', NOW()),
('Make My Trip (India ) Pvt.Ltd.', 'MAKE0509', NOW()),
('MAKS INDIA', 'MAKS0510', NOW()),
('Malik Road Lines', 'MALIK0511', NOW()),
('MANESAR HOTEL', 'MANES0512', NOW()),
('MANNU BHAI PRINTERS & ADVERTISERS', 'MANNU0513', NOW()),
('Manoj Singh', 'MANOJ0514', NOW()),
('Market Affaris', 'MARKE0515', NOW()),
('MARUTI NANDAN TRANSPORT', 'MARUT0516', NOW()),
('Meena Jain', 'MEENA0517', NOW()),
('METRO AIR CONDITIONERS', 'METRO0518', NOW()),
('Micro & Nanotechnologies', 'MICRO0519', NOW()),
('MITRASHMI EXPRESS SERVICES PRIVATE LIMITED', 'MITRA0520', NOW()),
('M J GASES PRIVATE LIMITED', 'MJG0521', NOW()),
('Mk Creations', 'MKCR0522', NOW()),
('MK Midha & Associates', 'MKMI0523', NOW()),
('MM Dotcom Graphics Pvt Ltd', 'MMDO0524', NOW()),
('MOHIT TYRES', 'MOHIT0525', NOW()),
('Moonlight Movers', 'MOONL0526', NOW()),
('Moreslides.Com Services Pvt.Ltd.', 'MORES0527', NOW()),
('MOTM TECHNOLOGIES', 'MOTM0528', NOW()),
('M.R. Enterprises', 'MR0529', NOW()),
('M.R. LOGISTICS INDIA PVT.LTD.', 'MR0530', NOW()),
('M/s Kritika Traders', 'MSK0531', NOW()),
('Muskan Computer & Peripherals', 'MUSKA0532', NOW()),
('M V M Jain & Associates', 'MVM0533', NOW()),
('Mysense Incorporation', 'MYSEN0534', NOW()),
('Mystair Hygiene Care Pvt.Ltd.', 'MYSTA0535', NOW()),
('Najin Export Pvt.Ltd.', 'NAJIN0536', NOW()),
('NARANG CROCKERY CENTER', 'NARAN0537', NOW()),
('Narender Singh', 'NAREN0538', NOW()),
('Naresh Electrical Industries', 'NARES0539', NOW()),
('National Aviation Company of India Ltd', 'NATIO0540', NOW()),
('National Freight Services', 'NATIO0541', NOW()),
('National Hardware Syndicate', 'NATIO0542', NOW()),
('National Wires & Cables Associate', 'NATIO0543', NOW()),
('Navnirmaan', 'NAVNI0544', NOW()),
('Neeti Malhotra', 'NEETI0545', NOW()),
('New Amar Road Carriers', 'NEWA0546', NOW()),
('NEW ARORA ROAD LINES', 'NEWA0547', NOW()),
('NEW DELHI RISHIKESH TRANSPORT SERVICE', 'NEWD0548', NOW()),
('New High Flying Travels Pvt.Ltd.', 'NEWH0549', NOW()),
('New Mann Transport Compnay', 'NEWM0550', NOW()),
('Next Events Pvt.Ltd.', 'NEXT0551', NOW()),
('N.H.Trading', 'NHT0552', NOW()),
('NIALL SERVICES', 'NIALL0553', NOW()),
('Nikhil Trading', 'NIKHI0554', NOW()),
('Nirpal Singh & Bros', 'NIRPA0555', NOW()),
('Nitco Logistics Pvt.Ltd.', 'NITCO0556', NOW()),
('Nitu Orient Roadline', 'NITU0557', NOW()),
('NOWFLOATS TECHNOLOGIES PVT LTD DRT SL A/c', 'NOWFL0558', NOW()),
('N S ENTERPRISES', 'NSE0559', NOW()),
('NUPUR BAJAJ', 'NUPUR0560', NOW()),
('OLYMPIA INDUSTRIES LIMITED', 'OLYMP0561', NOW()),
('Olympia Industries Ltd', 'OLYMP0562', NOW()),
('OM FREIGHT FORWARDERS PVT.LTD.', 'OMFR0563', NOW()),
('OM LOGISTICS LIMITED', 'OMLO0564', NOW()),
('OM PRANJAL MANAGEMENT SERVICES', 'OMPR0565', NOW()),
('Om Sai Ram Aircon Service', 'OMSA0566', NOW()),
('OM SWEETS PRIVATE LIMITED', 'OMSW0567', NOW()),
('Om Tyre Zone', 'OMTY0568', NOW()),
('Ondot Couriers & Cargo Ltd', 'ONDOT0569', NOW()),
('ONE LOGIN SUITE INC.', 'ONEL0570', NOW()),
('Osho Traders Services', 'OSHO0571', NOW()),
('Pacific Customs Broker Services Private Limited', 'PACIF0572', NOW()),
('PACKMILE PVT LTD', 'PACKM0573', NOW()),
('Pack & Move Transport Co.', 'PACK0574', NOW()),
('Pal Traders', 'PALT0575', NOW()),
('PARDHAN TYRE ZONE', 'PARDH0576', NOW()),
('PARI TRANSPORT COMPANY', 'PARI0577', NOW()),
('Paul Air Transport Pvt.Ltd.', 'PAUL0578', NOW()),
('Pawan Hardware', 'PAWAN0579', NOW()),
('Pehal Mart', 'PEHAL0580', NOW()),
('P G R & Co.', 'PGR0581', NOW()),
('P M Saree Wala', 'PMS0582', NOW()),
('Prabhati Lal & Sons', 'PRABH0583', NOW()),
('PRAKASH ENGINEERS & TRADERS', 'PRAKA0584', NOW()),
('Prakash Kochar & Co.', 'PRAKA0585', NOW()),
('Pramod Kumar', 'PRAMO0586', NOW()),
('P.R. Associates', 'PR0587', NOW()),
('Prem Chand', 'PREM0588', NOW()),
('Premsukhdas Shashikant', 'PREMS0589', NOW()),
('Pricise Systems and Solutions Pvt Ltd', 'PRICI0590', NOW()),
('Priya Sales Corporation', 'PRIYA0591', NOW()),
('Propac Sales And Services', 'PROPA0592', NOW()),
('Protean eGov Technologies Limited', 'PROTE0593', NOW()),
('PSP LOGISTIC', 'PSPL0594', NOW()),
('QTREK BUSINESS MANAGEMENT PVT.LTD.', 'QTREK0595', NOW()),
('QUALITY SOLUTIONS ( INDIA )', 'QUALI0596', NOW()),
('QUORUM CLUB LLP', 'QUORU0597', NOW()),
('RADIANT COMPUTERS', 'RADIA0598', NOW()),
('Radisson Blu Hotel Indore', 'RADIS0599', NOW()),
('Rafflex Square Developments Pvt.Ltd.', 'RAFFL0600', NOW()),
('RAHUL ENTERPRISES', 'RAHUL0601', NOW()),
('Raja Motors', 'RAJA0602', NOW()),
('RAJESH TRANSPORT COMPANY', 'RAJES0603', NOW()),
('Raj Kumar', 'RAJK0604', NOW()),
('Rama Logistics', 'RAMA0605', NOW()),
('RAMAN ELECTRICALS', 'RAMAN0606', NOW()),
('Rao Footwear', 'RAOF0607', NOW()),
('R C APPARELS', 'RCA0608', NOW()),
('RCPL Logistics Private Limited', 'RCPL0609', NOW()),
('RCPL Logistics Pvt.Ltd.', 'RCPL0610', NOW()),
('RCP ROADLINES', 'RCPR0611', NOW()),
('R D Retail', 'RDR0612', NOW()),
('Reachwell Worldwide Express', 'REACH0613', NOW()),
('Realike International', 'REALI0614', NOW()),
('Rekha Consultancy Services', 'REKHA0615', NOW()),
('R.E.Rogers India Pvt. Ltd .', 'RER0616', NOW()),
('Riddhi Siddhi  PACKAGING', 'RIDDH0617', NOW()),
('Right Products', 'RIGHT0618', NOW()),
('Rightways Air Logistics Pvt.Ltd.', 'RIGHT0619', NOW()),
('Rishab Glass & Plywood Co.', 'RISHA0620', NOW()),
('Rishabh Gupta Corp Private Limited', 'RISHA0621', NOW()),
('RITU MATTA', 'RITU0622', NOW()),
('RIVIGO SERVICES PVT.LTD.', 'RIVIG0623', NOW()),
('RIVONA HERBALS LLP', 'RIVON0624', NOW()),
('R.K. Electricals', 'RK0625', NOW()),
('ROAR GLOBAL LOGISTICS PVT.LTD.', 'ROAR0626', NOW()),
('Rock Pharmacy', 'ROCK0627', NOW()),
('R S Retails', 'RSR0628', NOW()),
('Rudra Enterprises', 'RUDRA0629', NOW()),
('Ryder Transport Service', 'RYDER0630', NOW()),
('SACHIN STEEL ENTERPRISES', 'SACHI0631', NOW()),
('Sachin Transport Service', 'SACHI0632', NOW()),
('SAFEXPRESS PRIVATE LIMITED', 'SAFEX0633', NOW()),
('Sagar Freight Carrier', 'SAGAR0634', NOW()),
('Sagar Resources', 'SAGAR0635', NOW()),
('Sahara India Roadlines', 'SAHAR0636', NOW()),
('Sai Labels', 'SAIL0637', NOW()),
('Sai Overseas Express', 'SAIO0638', NOW()),
('Samay Shatabdi Travels Pvt.Ltd.', 'SAMAY0639', NOW()),
('SAMIKSHA GARG & ASSOCIATES', 'SAMIK0640', NOW()),
('Sanjay Automotive', 'SANJA0641', NOW()),
('Santosh Transport Service', 'SANTO0642', NOW()),
('Sargam India Electronics Pvt.Ltd.', 'SARGA0643', NOW()),
('SBS SECURITY SERVICE & MANPOWER', 'SBSS0644', NOW()),
('SEABIRD MARINE SERVICES PVT.LTD.', 'SEABI0645', NOW()),
('SEATRANS AGENCIES (P) LTD', 'SEATR0646', NOW()),
('Sharma Battery House', 'SHARM0647', NOW()),
('SHARMA FIRE PROTECTION SERVICES', 'SHARM0648', NOW()),
('Shashi Sharma & Associates', 'SHASH0649', NOW()),
('Shatabdi Travels  Pvt . Ltd.', 'SHATA0650', NOW()),
('Shivam Enterprises', 'SHIVA0651', NOW()),
('Shiv Shakti Hardware & Electricals', 'SHIV0652', NOW()),
('Shree Balaji Maruti Spare Parts', 'SHREE0653', NOW()),
('Shree Mahvir Communications', 'SHREE0654', NOW()),
('Shree Nasik Goods Transport Co.Pvt.Ltd.', 'SHREE0655', NOW()),
('Shree Om Sainath Roadways', 'SHREE0656', NOW()),
('SHREE SAI', 'SHREE0657', NOW()),
('SHREE SHYAM ELECTRICALS', 'SHREE0658', NOW()),
('Shree Shyam Traders', 'SHREE0659', NOW()),
('Shrinath Cargo Pvt. Ltd.', 'SHRIN0660', NOW()),
('SHRI RAM PACKAGING', 'SHRI0661', NOW()),
('Shri Ram Welding Material & Hardware', 'SHRI0662', NOW()),
('Shri Shyam Enterprises', 'SHRI0663', NOW()),
('SHUBH PROJECTION', 'SHUBH0664', NOW()),
('SHUKLA MISHRA & CO', 'SHUKL0665', NOW()),
('Shyam Hardware Store', 'SHYAM0666', NOW()),
('SHYAM SPECTRA PVT.LTD.', 'SHYAM0667', NOW()),
('Sigma Logistics', 'SIGMA0668', NOW()),
('Sigma Seo Solution Pvt.Ltd.', 'SIGMA0669', NOW()),
('Sky Global', 'SKYG0670', NOW()),
('Skylark Sales Corporation', 'SKYLA0671', NOW()),
('SMARTSHIFT LOGISTICS SOLUTIONS PRIVATE LIMITED', 'SMART0672', NOW()),
('SNV AVIATION PVT.LTD.', 'SNVA0673', NOW()),
('Solutions India', 'SOLUT0674', NOW()),
('Som Logistic Solutions Pvt.Ltd.', 'SOML0675', NOW()),
('Sorich Organics Pvt.Ltd.', 'SORIC0676', NOW()),
('Speedsafe Courier & Cargo Service', 'SPEED0677', NOW()),
('SpiceJet Limited', 'SPICE0678', NOW()),
('SPOTON LOGISTICS PVT LTD', 'SPOTO0679', NOW()),
('SPRINT LOGISTICS PVT.LTD.', 'SPRIN0680', NOW()),
('SRI SAI VIVEKA TECHNOLOGIES', 'SRIS0681', NOW()),
('S S UNIFORMS', 'SSU0682', NOW()),
('Standard Electricals', 'STAND0683', NOW()),
('Stander Singh Yadav', 'STAND0684', NOW()),
('Star Beverage System', 'STAR0685', NOW()),
('STYLE WEARS', 'STYLE0686', NOW()),
('Subhash Kumar Jha', 'SUBHA0687', NOW()),
('SUMESH CRANE SERVICE', 'SUMES0688', NOW()),
('SUNARIYA INDUSTRIAL TRADERS', 'SUNAR0689', NOW()),
('SUN EXPORT PRIVATE LIMITED', 'SUNE0690', NOW()),
('SUNFINITI ENTERPRISES', 'SUNFI0691', NOW()),
('SUNNY TRANSPORT CORPORATION', 'SUNNY0692', NOW()),
('Sunrise Packaging', 'SUNRI0693', NOW()),
('SUNTEK AXPRESS INDIA PVT.LTD.', 'SUNTE0694', NOW()),
('Supreme Spares Pvt.Ltd.', 'SUPRE0695', NOW()),
('SURENDER KR.SINGHAL CO', 'SUREN0696', NOW()),
('Surender Pal', 'SUREN0697', NOW()),
('Suresh Kumar Transport Co.', 'SURES0698', NOW()),
('Surjeet Singh', 'SURJE0699', NOW()),
('SWIFT AIR TRANSPEED PVT LTD', 'SWIFT0700', NOW()),
('Swiftline Transport Solutions Pvt.Ltd.', 'SWIFT0701', NOW()),
('Tadad Singh', 'TADAD0702', NOW()),
('Tara Hardware & Electrical', 'TARA0703', NOW()),
('Target Integration Consultancy Pvt.Ltd.', 'TARGE0704', NOW()),
('Tarsem Lal', 'TARSE0705', NOW()),
('TATA AIG General Insurance Co. Ltd.', 'TATA0706', NOW()),
('TATA CAPITAL FINANCIAL SERVICES LTD.', 'TATA0707', NOW()),
('TATA CAPITAL HOUSING FINANCE LTD', 'TATA0708', NOW()),
('TATA General Insurance Co Ltd', 'TATA0709', NOW()),
('TATA POWER TRADING COMPANY LTD', 'TATA0710', NOW()),
('Tata Sia Airlines Ltd', 'TATA0711', NOW()),
('TATA TELESEVICES LTD', 'TATA0712', NOW()),
('Tech2Globe Web Solutions Llp', 'TECH20713', NOW()),
('TECHMOJITO', 'TECHM0714', NOW()),
('Techno Commercial Services', 'TECHN0715', NOW()),
('Techproc-C Lientcod', 'TECHP0716', NOW()),
('Tech Route Logistics Private Limited', 'TECH0717', NOW()),
('Tech Tribe Infoways', 'TECH0718', NOW()),
('Telenity Systems Software India Pvt.Ltd.', 'TELEN0719', NOW()),
('Thai Airways International Pubic Co.Ltd.', 'THAI0720', NOW()),
('The Brand Lab', 'THEB0721', NOW()),
('THE INDIAN VACATION', 'THEI0722', NOW()),
('The Minni Track Union', 'THEM0723', NOW()),
('The Nalagarh Truck Operation,S Union Nalagarh', 'THEN0724', NOW()),
('The Oriental Insurance Company Ltd.', 'THEO0725', NOW()),
('The Quest', 'THEQ0726', NOW()),
('The Truck Union Kasan', 'THET0727', NOW()),
('Tirupati Courier Service Pvt.Ltd.', 'TIRUP0728', NOW()),
('TNS Institute of Information Technology Pvt. Ltd.', 'TNSI0729', NOW()),
('Toyota Financial Services India Ltd', 'TOYOT0730', NOW()),
('Track Nternational Trading Pvt.Ltd', 'TRACK0731', NOW()),
('TRACK WORLD VACATIONS PVT.LTD.', 'TRACK0732', NOW()),
('TRADE CENTRE HOSPITALITY LLP', 'TRADE0733', NOW()),
('TRANSMEC ( INDIA ) PRIVATE LIMITED', 'TRANS0734', NOW()),
('Transport Corporation of India Ltd', 'TRANS0735', NOW()),
('Travel  O Holiday', 'TRAVE0736', NOW()),
('Travel on Call', 'TRAVE0737', NOW()),
('Triton Hotels and Resorts Pvt.Ltd.', 'TRITO0738', NOW()),
('TRUBLU SOLUTIONS', 'TRUBL0739', NOW()),
('True Cartridge', 'TRUE0740', NOW()),
('Tvisha Enterprises', 'TVISH0741', NOW()),
('TYREVOLUTION', 'TYREV0742', NOW()),
('Umesh Traders', 'UMESH0743', NOW()),
('Unilife', 'UNILI0744', NOW()),
('UNIQUE CARRIERS PVT. LTD.', 'UNIQU0745', NOW()),
('United Indias Insurance Company Ltd', 'UNITE0746', NOW()),
('Uniyal Transport Corporaton', 'UNIYA0747', NOW()),
('UPS Express Pvt.Ltd.', 'UPSE0748', NOW()),
('Urban Pest Control Pvt.Ltd.', 'URBAN0749', NOW()),
('U. S. Transport Company', 'US0750', NOW()),
('Uttam Chand Mahajan & Sons', 'UTTAM0751', NOW()),
('Vac Air Techonologies', 'VACA0752', NOW()),
('VAISHALI PRINTERS', 'VAISH0753', NOW()),
('Vandana Electrical Mehanical Works', 'VANDA0754', NOW()),
('Varish International', 'VARIS0755', NOW()),
('Vashudev Jain and Com.', 'VASHU0756', NOW()),
('Vee Aar Rides Private Limited', 'VEEA0757', NOW()),
('VIGHNAHAR SALES AND SERVICES', 'VIGHN0758', NOW()),
('Vikas Chopra', 'VIKAS0759', NOW()),
('Vikas Jain', 'VIKAS0760', NOW()),
('Vikas Kumar', 'VIKAS0761', NOW()),
('Vimbri Media Pvt.Ltd.', 'VIMBR0762', NOW()),
('Vinayak Electricals', 'VINAY0763', NOW()),
('VINTAGE ENTERPRISES', 'VINTA0764', NOW()),
('Vipul Trade', 'VIPUL0765', NOW()),
('VODAFONE  IDEA  LTD', 'VODAF0766', NOW()),
('Voice Tree Technologies Pvt.Ltd.', 'VOICE0767', NOW()),
('Vrrddhi Freight Pvt.Ltd.', 'VRRDD0768', NOW()),
('V.S. Interchem Pvt. Ltd.', 'VS0769', NOW()),
('V TRANS (INDIA) LIMITED', 'VTRA0770', NOW()),
('WEB2TECH SOLUTIONS', 'WEB2T0771', NOW()),
('WEBLINK.IN PVT.LTD.', 'WEBLI0772', NOW()),
('WHEELSEYE TECHNOLOGY INDIA PRIVATE LIMITED', 'WHEEL0773', NOW()),
('WIZ Logitec Solutions Pvt.Ltd.', 'WIZL0774', NOW()),
('WNT CAR CARE', 'WNTC0775', NOW()),
('Xiaomi Technology India Pvt. Ltd', 'XIAOM0776', NOW()),
('YADAV COOL POINT', 'YADAV0777', NOW()),
('Yadav Courier & Cargo', 'YADAV0778', NOW()),
('YADAV MECHANICAL WORKS', 'YADAV0779', NOW()),
('YADAV TEMPO SERVICE', 'YADAV0780', NOW()),
('Yash Associates', 'YASH0781', NOW()),
('Zoho Technologies Pvt.Ltd.', 'ZOHO0782', NOW()),
('PRESTO STANTEST PRIVATE LIMITED', 'PREST0783', NOW()),
('A.K. MACHINERY', 'AK0784', NOW()),
('APMP MOTORS LLP', 'APMP0785', NOW()),
('Art-N-Glass Inc.', 'ARTN0786', NOW()),
('BEACON ELEVATOR CO.P.LTD.', 'BEACO0787', NOW()),
('B M MOTORS', 'BMM0788', NOW()),
('Bose Corporation India Pvt.Ltd.', 'BOSE0789', NOW()),
('CROSSSALES.IN', 'CROSS0790', NOW()),
('Dhingra Motors Pvt.Ltd.', 'DHING0791', NOW()),
('Dyson Technology India Pvt.Ltd.', 'DYSON0792', NOW()),
('EASHANYA ELECTRICALS & PAINTS', 'EASHA0793', NOW()),
('GALAXY PACKAGING MACHINE', 'GALAX0794', NOW()),
('Infiniti Retail Ltd', 'INFIN0795', NOW()),
('JANGRA ELECTRONICS', 'JANGR0796', NOW()),
('JINDAL FURNITURE SYSTEMS', 'JINDA0797', NOW()),
('Just Bicycle & Accessories', 'JUST0798', NOW()),
('NAVYUG ENTERPRISES', 'NAVYU0799', NOW()),
('NCR MOTORS INDIA PVT. LTD.', 'NCRM0800', NOW()),
('NEWVIK TELESERVICES', 'NEWVI0801', NOW()),
('NOUVEL ELEMENTS', 'NOUVE0802', NOW()),
('PRAKASH ELECTRIC COMPANY', 'PRAKA0803', NOW()),
('RAKESH ELECTRONICS', 'RAKES0804', NOW()),
('Refresh Technology Pvt.Ltd.', 'REFRE0805', NOW()),
('Sai Automobiles', 'SAIA0806', NOW()),
('Shiv Body Works', 'SHIV0807', NOW()),
('Shree Balaji Trading Company', 'SHREE0808', NOW()),
('SINCERE MARKETING SERVICES PVT LTD', 'SINCE0809', NOW()),
('Techno Print Chemicals Pvt.Ltd.', 'TECHN0810', NOW()),
('T & T Motors Pvt. Ltd.', 'TT0811', NOW()),
('Unicorn Infosolutions Pvt.Ltd.', 'UNICO0812', NOW()),
('United Traders', 'UNITE0813', NOW()),
('VIJAY SALES (INDIA) PRIVATE LIMITED', 'VIJAY0814', NOW()),
('Alkesh Chaudhary', 'ALKES0815', NOW()),
('Ansh Motor Service', 'ANSH0816', NOW()),
('APS ADVISORS LLP', 'APSA0817', NOW()),
('Ashish  Sharma', 'ASHIS0818', NOW()),
('Chanderadev  Sharma', 'CHAND0819', NOW()),
('Dinesh Kumar ( Transporter )', 'DINES0820', NOW()),
('Gourav Mahesh & Associates', 'GOURA0821', NOW()),
('GPS Consultants', 'GPSC0822', NOW()),
('K G & ASSOCIATES', 'KG0823', NOW()),
('Krishan Kumar', 'KRISH0824', NOW()),
('Krishna Devi', 'KRISH0825', NOW()),
('Lalji Mulji Transport Co.', 'LALJI0826', NOW()),
('Maan Singh', 'MAAN0827', NOW()),
('Manoj Kumar', 'MANOJ0828', NOW()),
('Pankaj Mahesh & Co', 'PANKA0829', NOW()),
('Perfect Management Services', 'PERFE0830', NOW()),
('Prince Road Lines', 'PRINC0831', NOW()),
('Sawarn Generator', 'SAWAR0832', NOW()),
('Shiv Charan', 'SHIV0833', NOW()),
('SIYA RAM MINI TRANSPORT', 'SIYA0834', NOW()),
('SUBIR P CHOURE', 'SUBIR0835', NOW()),
('SUNIL KUMAR', 'SUNIL0836', NOW()),
('3WAYS PACKAGING & LASHING SERVICES', '3WAYS0837', NOW()),
('AAIDEA SOLUTIONS PRIVATE LIMITED', 'AAIDE0838', NOW()),
('AAIDEA SOLUTIONS PVT. LTD.', 'AAIDE0839', NOW()),
('ACME AUTOMATION PVT. LTD.', 'ACME0840', NOW()),
('ACTIVE SYSTEMS', 'ACTIV0841', NOW()),
('ADARSHA  PACKAGING PVT LTD', 'ADARS0842', NOW()),
('ADARSH ELECTROPLATING WORKS', 'ADARS0843', NOW()),
('ADCON', 'ADCON0844', NOW()),
('ADITYA PACKAGING AND CONSULTING SERVICES PVT. LTD.', 'ADITY0845', NOW()),
('ADITYA TECHNO SALES', 'ADITY0846', NOW()),
('ADVANCE ENGINEERING', 'ADVAN0847', NOW()),
('AFFECTUS TECHNOTOOLS', 'AFFEC0848', NOW()),
('Agarwal Packers and Movers Limited', 'AGARW0849', NOW()),
('AGILE NOBEL', 'AGILE0850', NOW()),
('AGRAWAL METAL WORKS PVT.LTD.', 'AGRAW0851', NOW()),
('AGRAWAL METAL WORKS PVT.LTD. ( H )', 'AGRAW0852', NOW()),
('AGS FOURWINDS INDIA PVT LTD.', 'AGSF0853', NOW()),
('Ahresty India Pvt. Ltd.', 'AHRES0854', NOW()),
('AIRA EURO AUTOMATION PRIVATE LIMITED', 'AIRA0855', NOW()),
('AIRTEC ELECTROVISION PRIVATE LIMITED', 'AIRTE0856', NOW()),
('AISIN AUTOMOTIVE HARYANA PRIVATE LIMITED', 'AISIN0857', NOW()),
('ALIA ENTERPRISES', 'ALIA0858', NOW()),
('ALISHA PLASTICS', 'ALISH0859', NOW()),
('ALLESPACK SYSTEMS PRIVATE LIMITED', 'ALLES0860', NOW()),
('ALLIED JB FRICTION PRIVATE LIMITED', 'ALLIE0861', NOW()),
('ALLIED SPARES & AUTO PARTS MANUFACTURING COMPANY P RIVATE LIMITED', 'ALLIE0862', NOW()),
('ALLSTAR CONSERV PVT. LTD.', 'ALLST0863', NOW()),
('Alpha Packaging', 'ALPHA0864', NOW()),
('AMALGAMATIONS VALEO CLUTCH PVT. LTD.', 'AMALG0865', NOW()),
('Ambey Wood Packer', 'AMBEY0866', NOW()),
('AMIRA PURE FOODS PRIVATE LIMITED', 'AMIRA0867', NOW()),
('Ample Autotech Pvt Ltd.', 'AMPLE0868', NOW()),
('AMRIT FILTRONICS INDIA', 'AMRIT0869', NOW()),
('AMTEK AUTO LIMITED', 'AMTEK0870', NOW()),
('AMTEK AUTO LIMITED ( Plot No. - 01 )', 'AMTEK0871', NOW()),
('Amtek Auto Limited ( Shed No. 1 & 2 )', 'AMTEK0872', NOW()),
('Amtek Auto Ltd.', 'AMTEK0873', NOW()),
('AMTEK AUTO Ltd. (Plot No. 20 )', 'AMTEK0874', NOW()),
('AMTEK POWERTRAIN LIMITED', 'AMTEK0875', NOW()),
('AMTEK TRANSPORTATION SYSTEM LIMITED', 'AMTEK0876', NOW()),
('AMZEN TECHNOLOGIES PRIVATE LIMITED', 'AMZEN0877', NOW()),
('ANAND ELECTROPLATERS', 'ANAND0878', NOW()),
('ANISHA PACKAGING', 'ANISH0879', NOW()),
('Anishi Enterprises', 'ANISH0880', NOW()),
('ANSHIKA ENTERPRISES', 'ANSHI0881', NOW()),
('ANVIDHA TECHNOLOGIES PRIVATE LIMITED', 'ANVID0882', NOW()),
('A ONE INDUSTRIAL PACKAGING SOLUTIONS', 'AONE0883', NOW()),
('APL Logistics India Private Limited ( Rudrapur )', 'APLL0884', NOW()),
('APL LOGISTICS INDIA PVT LTD', 'APLL0885', NOW()),
('APPLIED AUTO PARTS PVT. LTD.', 'APPLI0886', NOW()),
('APPLIED TECHNO PRODUCTS PVT.LTD.', 'APPLI0887', NOW()),
('APPL PACKAGING', 'APPL0888', NOW()),
('APT TOOLS & MACHINERY (INDIA)PRIVATE LIMITED', 'APTT0889', NOW()),
('A.R.AUTOMOTIVE SOLUTION', 'ARA0890', NOW()),
('ARB Bearings Limited', 'ARBB0891', NOW()),
('ARBIN STEEL FAB PRIVATE LIMITED', 'ARBIN0892', NOW()),
('ARGL LTD', 'ARGL0893', NOW()),
('ARGL LTD''', 'ARGL0894', NOW()),
('ARKEY ENGINEERING INDUSTRIES', 'ARKEY0895', NOW()),
('ARNAF FUTURISTIC TECHNOLOGIES PRIVATE LIMITED', 'ARNAF0896', NOW()),
('Artistic Indians', 'ARTIS0897', NOW()),
('Arvind Automotive (India) Pvt Ltd. -(UNIT-II)', 'ARVIN0898', NOW()),
('ASH HAMMER UNION', 'ASHH0899', NOW()),
('ASHNOOR TEXTILE MILL LTD.', 'ASHNO0900', NOW()),
('ASK Automotive Limited Unit-XII', 'ASKA0901', NOW()),
('ASK Automotive Pvt. Ltd. UNIT-II', 'ASKA0902', NOW()),
('ASK Automotive Pvt. Ltd. UNIT- VII', 'ASKA0903', NOW()),
('ASP SEALING PRODUCTS LTD.', 'ASPS0904', NOW()),
('ASSOCIATED CONTIANER TERMINALS LIMITED', 'ASSOC0905', NOW()),
('Astro Packaging Solutions', 'ASTRO0906', NOW()),
('AUTOMETERS ENERGITEC LIMITED', 'AUTOM0907', NOW()),
('Auto Parts Solutions Pvt. Ltd.', 'AUTO0908', NOW()),
('AVGOL INDIA PRIVATE LIMITED', 'AVGOL0909', NOW()),
('AVM HEALTH CARE PRODUCTS PRIVATE LIMITED', 'AVMH0910', NOW()),
('AVVASHYA CCI LOGISTICS PRIVATE LIMITED', 'AVVAS0911', NOW()),
('A-WIN ENTERPRISES PRIVATE LIMITED', 'AWIN0912', NOW()),
('BADVE ENGINEERING LTD. UNIT-14', 'BADVE0913', NOW()),
('BAJAJ MOTORS LIMITED', 'BAJAJ0914', NOW()),
('BALAJI PRECISION COMPONENTS PVT. LTD.', 'BALAJ0915', NOW()),
('Bala Ji Precission Component', 'BALA0916', NOW()),
('BALAJI WOOD WORK', 'BALAJ0917', NOW()),
('Balancing Bits', 'BALAN0918', NOW()),
('BALONI ENGINEERING PVT. LTD.', 'BALON0919', NOW()),
('BANCO GASKETS (INDIA) LIMITED', 'BANCO0920', NOW()),
('Baxy Limited', 'BAXY0921', NOW()),
('BEETA TECHNOLOGIES', 'BEETA0922', NOW()),
('BENARA UDYOG LIMITED', 'BENAR0923', NOW()),
('BESOTO STARTING SYSTEMS PVT LTD.', 'BESOT0924', NOW()),
('Bhagwan Auto Products', 'BHAGW0925', NOW()),
('BHAGWAN DASS & SONS FASTNERS PRIVATE LIMITED', 'BHAGW0926', NOW()),
('BHAGWATI ENGINEERING WORKS', 'BHAGW0927', NOW()),
('Bharat Forge Limited', 'BHARA0928', NOW()),
('BHARAT HEAVY ELECTRICALS LTD', 'BHARA0929', NOW()),
('BISON INDUSTRIAL PACKAGING', 'BISON0930', NOW()),
('BLUE STAMPINGS & FORGINGS LTD', 'BLUE0931', NOW()),
('Bosch Limited', 'BOSCH0932', NOW()),
('BOSCH LIMITED ( Jaipur )', 'BOSCH0933', NOW()),
('Bosch LTD. ( PUNE )', 'BOSCH0934', NOW()),
('Bosch Rexroth (India) Pvt. Ltd.', 'BOSCH0935', NOW()),
('BREMBO BRAKE INDIA PRIVATE LIMITED', 'BREMB0936', NOW()),
('BRIGHT ENTERPRISES', 'BRIGH0937', NOW()),
('Broadway Freight', 'BROAD0938', NOW()),
('BROADWAY FREIGHT FORWARDING', 'BROAD0939', NOW()),
('B S CORPORATION', 'BSC0940', NOW()),
('BSP PACKAGING PRIVATE LIMITED', 'BSPP0941', NOW()),
('Bucher Hydraulics Pvt .Ltd', 'BUCHE0942', NOW()),
('BUSCH VACUUM INDIA PVT. LTD.', 'BUSCH0943', NOW()),
('C AND S ELECTRIC LIMITED', 'CAND0944', NOW()),
('Caparo Maruti Ltd.', 'CAPAR0945', NOW()),
('Capsugel Healthcare Private Limited', 'CAPSU0946', NOW()),
('CASCY FORGE PRODUCTS', 'CASCY0947', NOW()),
('CASTEX TECHNOLOGIES LIMITED (DIAMOND)', 'CASTE0948', NOW()),
('Castex Technologies Ltd. - Machining', 'CASTE0949', NOW()),
('CHANDERPUR INDUSTRIES PVT. LTD', 'CHAND0950', NOW()),
('CHANDERPUR WORKS PRIVATE LIMITED', 'CHAND0951', NOW()),
('CHANDRA ENGINEERS', 'CHAND0952', NOW()),
('CHARU PACKING INDUSTRIES', 'CHARU0953', NOW()),
('CHETNA ENTERPRISES', 'CHETN0954', NOW()),
('CHILLPILL VENTURE PRIVATE LIMITED', 'CHILL0955', NOW()),
('CIKAUTXO INDIA PRIVATE LIMITED', 'CIKAU0956', NOW()),
('CLAAS INDIA PVT. LTD.', 'CLAAS0957', NOW()),
('CLAN WITS INDIA PVT. LTD.', 'CLAN0958', NOW()),
('CLEAR PACKAGING PRIVATE LIMITED', 'CLEAR0959', NOW()),
('Climax Overseas Pvt.Ltd.', 'CLIMA0960', NOW()),
('CMTHYDRO RESEARCH AND DEVELOPMENT PRIVATE LIMITED', 'CMTHY0961', NOW()),
('CNC MACHINING TECHNOLOGY', 'CNCM0962', NOW()),
('Columbus Integration Services Pvt. Ltd.', 'COLUM0963', NOW()),
('COMBINED ENGINEERINGS PRIVATE LIMITED', 'COMBI0964', NOW()),
('Compact India Pvt. Ltd.', 'COMPA0965', NOW()),
('CONCEPT PACKAGING ( S )', 'CONCE0966', NOW()),
('Conic Automotive Pvt. Ltd', 'CONIC0967', NOW()),
('CONSOLIDATED COIN COMPANY PVT. LTD.', 'CONSO0968', NOW()),
('CONSUL NEOWATT POWER SOLUTIONS PVT. LTD.', 'CONSU0969', NOW()),
('CONTINENTAL ENGINES PRIVATE LIMITED', 'CONTI0970', NOW()),
('Contitech India Private Limited', 'CONTI0971', NOW()),
('Coolwinks Technologies Private Limited', 'COOLW0972', NOW()),
('CORROSHIELD ENTERPRISES', 'CORRO0973', NOW()),
('CRAFTSMAN AUTOMATION LIMITED ( Faridabad )', 'CRAFT0974', NOW()),
('CRAFTSMAN AUTOMATION LIMITED ( Pune )', 'CRAFT0975', NOW()),
('CREDENCE ENGINEERING SERVICES', 'CREDE0976', NOW()),
('CREST LASHING AND PACKAGING PRIVATE LTD', 'CREST0977', NOW()),
('C & S ELECTRIC LIMITED ( Uttarakhand )', 'CS0978', NOW()),
('C&S Electric Ltd', 'CSE0979', NOW()),
('CUIR INDE', 'CUIR0980', NOW()),
('Daido India Pvt. Ltd.', 'DAIDO0981', NOW()),
('DAKSH INDIA', 'DAKSH0982', NOW()),
('DAKSH INDIA ORGANICS', 'DAKSH0983', NOW()),
('DALMIA POLYMERS LLP', 'DALMI0984', NOW()),
('Dantal Hydraulics Private Limited', 'DANTA0985', NOW()),
('DARSHAN LAL & CO.', 'DARSH0986', NOW()),
('DATTA RUBBER INDUSTRIES', 'DATTA0987', NOW()),
('Dayco  Power Transmission ( P) Ltd.', 'DAYCO0988', NOW()),
('DEE EMM GIKEN (P) LTD.', 'DEEE0989', NOW()),
('DEE-KAY GEARS', 'DEEK0990', NOW()),
('Deep Machine Tools', 'DEEP0991', NOW()),
('Defence Land Systems India Limited', 'DEFEN0992', NOW()),
('DELPHI TVS TECHNOLOGIES LIMITED', 'DELPH0993', NOW()),
('Denso Haryana (P) Ltd.', 'DENSO0994', NOW()),
('Denso Haryana Pvt. Ltd. (Jhajjar)', 'DENSO0995', NOW()),
('DENSO INTERNATIONAL INDIA PVT. LTD.', 'DENSO0996', NOW()),
('DEUSCH KYOSEI ENGINEERING PRIVATE LIMITED', 'DEUSC0997', NOW()),
('DEUSCH KYOSEI ENGINEERING PVT. LTD.', 'DEUSC0998', NOW()),
('DHAWAN ENTERPRISES', 'DHAWA0999', NOW()),
('DHIMAN ENGINEERS', 'DHIMA1000', NOW()),
('DM EXPRESS', 'DMEX1001', NOW()),
('Dolphin Packers and Movers', 'DOLPH1002', NOW()),
('Dolphin Packers & Movers', 'DOLPH1003', NOW()),
('Dornier Machinery India Pvt.Ltd.', 'DORNI1004', NOW()),
('DOZCO INDIA PVT. LTD.', 'DOZCO1005', NOW()),
('DROPCO MULTILUB  SYSTEMS PVT. LTD.', 'DROPC1006', NOW()),
('D.S.ENGINEERS', 'DSE1007', NOW()),
('DUISPORT PACKING LOGISTICS INDIA PVT. LTD.', 'DUISP1008', NOW()),
('Duroshox Pvt. Ltd.', 'DUROS1009', NOW()),
('DYNAMIC ROBOTICS', 'DYNAM1010', NOW()),
('Dynatech Controls (P) Ltd', 'DYNAT1011', NOW()),
('EASTERN ALLOYS PVT. LTD.', 'EASTE1012', NOW()),
('Eaton Power Quality Pvt.Ltd.', 'EATON1013', NOW()),
('ECO INDIA PRIVATE LIMITED', 'ECOI1014', NOW()),
('EKDANTA CORPORATION', 'EKDAN1015', NOW()),
('ELECTRACON PARADISE LIMITED ( Haryana )', 'ELECT1016', NOW()),
('ELECTRACON PARADISE LTD.', 'ELECT1017', NOW()),
('Electrospark', 'ELECT1018', NOW()),
('Elements Exports Pvt. Ltd.', 'ELEME1019', NOW()),
('ELITEPAC SOLUTION', 'ELITE1020', NOW()),
('EMMBROS AUTOCOMP LIMITED', 'EMMBR1021', NOW()),
('EMMFORCE INC', 'EMMFO1022', NOW()),
('ENPAY TRANSFORMER COMPONENTS INDIA PVT. LTD.', 'ENPAY1023', NOW()),
('ENSTO INDIA PRIVATE LIMITED', 'ENSTO1024', NOW()),
('EPENEZER Packaging', 'EPENE1025', NOW()),
('ESCORTS KUBOTA INDIA PRIVATE LIMITED', 'ESCOR1026', NOW()),
('ESTHETICA SPA SALON RESOURCES PVT. LTD.', 'ESTHE1027', NOW()),
('ESWAR TECHNO SOLUTIONS', 'ESWAR1028', NOW()),
('EXCAVA ATTACHERS PRIVATE LIMITED', 'EXCAV1029', NOW()),
('EXCEL CONTROLINKAGE PVT LTD', 'EXCEL1030', NOW()),
('EXCELLENT ENTERPRISES', 'EXCEL1031', NOW()),
('EYEMYEYE PRIVATE LIMITED', 'EYEMY1032', NOW()),
('FABINDIA LIMITED', 'FABIN1033', NOW()),
('FABINDIA LIMITED ( Haryana )', 'FABIN1034', NOW()),
('FAIVELEY TRANSPORT RAIL TECHNOLOGIES', 'FAIVE1035', NOW()),
('FALCON AUTO ENGINEERING PRIVATE LIMITED', 'FALCO1036', NOW()),
('FANUC India Private Limited', 'FANUC1037', NOW()),
('FEDELE AUTOCORE PRIVATE LIMITED', 'FEDEL1038', NOW()),
('FENESTA BUILDING SYSTEMS', 'FENES1039', NOW()),
('FFP PRODUCTS', 'FFPP1040', NOW()),
('Fiat India Automobiles Ltd', 'FIAT1041', NOW()),
('FIBRO INDIA PRECISION  PRODUCTS  PVT. LTD.', 'FIBRO1042', NOW()),
('FINE FINISH ORGANICS PRIVATE LIMITED', 'FINE1043', NOW()),
('FINPACK SOLUTIONS', 'FINPA1044', NOW()),
('Flame-Ex', 'FLAME1045', NOW()),
('FLASHKART INDIA PRIVATE LIMITED', 'FLASH1046', NOW()),
('FOCUS ENTERPRISE', 'FOCUS1047', NOW()),
('FORCE MOTORS LIMITED', 'FORCE1048', NOW()),
('FORCE MOTORS LTD.', 'FORCE1049', NOW()),
('Foundation Brake Manufacturing Pvt.Ltd. ( Manesar)', 'FOUND1050', NOW()),
('GADIN ENTERPRISES', 'GADIN1051', NOW()),
('GALAXY LOGISTICS', 'GALAX1052', NOW()),
('Gallay India (P) Ltd.', 'GALLA1053', NOW()),
('Gallium Care', 'GALLI1054', NOW()),
('Ganga Electricals india pvt ltd', 'GANGA1055', NOW()),
('Ganwal Engineering', 'GANWA1056', NOW()),
('GANWAL ESECURE PRIVATE LIMITED', 'GANWA1057', NOW()),
('GATES UNITTA INDIA COMPANY PVT. LTD.', 'GATES1058', NOW()),
('G D ENTERPRISE', 'GDE1059', NOW()),
('GEE PEE INDUSTRIES', 'GEEP1060', NOW()),
('GESCON (1961) PVT LTD', 'GESCO1061', NOW()),
('Ghai Mining Tools Corporation (P) Ltd.', 'GHAI1062', NOW()),
('GINDRE INDIA COMPONENTS PRIVATE LIMITED', 'GINDR1063', NOW()),
('GINDRE INDIA COMPONENTS PVT. LTD.', 'GINDR1064', NOW()),
('GNA Axel Ltd', 'GNAA1065', NOW()),
('GOELA ENGINEERS (OVERSEAS)', 'GOELA1066', NOW()),
('Gomsons Industries', 'GOMSO1067', NOW()),
('Goodwill Hi-Precision Works', 'GOODW1068', NOW()),
('G.R. & COMPANY', 'GR1069', NOW()),
('GREEN PACKS', 'GREEN1070', NOW()),
('GREEN PACKS DS PACKING SOLUTIONS PRIVATE LIMITED', 'GREEN1071', NOW()),
('Greno Packaging Industries', 'GRENO1072', NOW()),
('GRIT MANUFACTURERS AND TRADERS.', 'GRIT1073', NOW()),
('G S LOGISTICS PVT LTD', 'GSL1074', NOW()),
('G V MEDITECH PRIVATE LIMITED', 'GVM1075', NOW()),
('HANKYU HANSHIN EXPRESS INDIA PRIVATE LIMITED', 'HANKY1076', NOW()),
('HARI NARAYAN', 'HARI1077', NOW()),
('HARI OM ENTERPRISES', 'HARI1078', NOW()),
('HAWKS ENTERPRISES', 'HAWKS1079', NOW()),
('HENDRIK INDUSTRIES', 'HENDR1080', NOW()),
('HERO CYCLES LIMITED', 'HERO1081', NOW()),
('HEXAGON METROLOGY INDIA PVT. LTD.', 'HEXAG1082', NOW()),
('HGI AUTOMOTIVES PRIVATE LIMITED', 'HGIA1083', NOW()),
('HIGH DESIGN AUTO', 'HIGH1084', NOW()),
('Hi- LEX India Private Limited', 'HIL1085', NOW()),
('HIMMEL TECHNOLOGIES PVT. LTD.', 'HIMME1086', NOW()),
('HIND PACKAGING', 'HIND1087', NOW()),
('HIRJI LOGIPACK PRIVATE LIMITED', 'HIRJI1088', NOW()),
('HI-TECH ARAI PRIVATE LIMITED', 'HITE1089', NOW()),
('HMC MM AUTO LIMITED', 'HMCM1090', NOW()),
('Holisol Logistics Pvt. Limited', 'HOLIS1091', NOW()),
('HOLISOL LOGISTICS PVT. LTD. ( Delhi )', 'HOLIS1092', NOW()),
('Holisol Logistics Pvt. Ltd. (G)', 'HOLIS1093', NOW()),
('HONDA CARS INDIA LIMITED', 'HONDA1094', NOW()),
('HONDA CARS INDIA LTD.', 'HONDA1095', NOW()),
('Honda Motorcycle and Scooter India (P) Ltd.', 'HONDA1096', NOW()),
('HONDA MOTORCYCLE AND SCOOTER INDIA PRIVATE LIMITED', 'HONDA1097', NOW()),
('HORIZON AEROSPACE (INDIA) PRIVATE LIMITED', 'HORIZ1098', NOW()),
('HORIZON MERCANTILE ASSOCIATES PRIVATE LIMITED', 'HORIZ1099', NOW()),
('HORIZON PACKS PRIVATE LIMITED', 'HORIZ1100', NOW()),
('HVS AGENCIES', 'HVSA1101', NOW()),
('HWB Technologies', 'HWBT1102', NOW()),
('HY- Power Clamps Pvt.Ltd.', 'HYP1103', NOW()),
('IDAM PERFUMERS LLP', 'IDAM1104', NOW()),
('IJTC TECHNOLOGIES PRIVATE LIMITED', 'IJTC1105', NOW()),
('IKEN AUTOMATIONS PRIVATE LIMITED', 'IKEN1106', NOW()),
('Imperial Auto Industries Limited', 'IMPER1107', NOW()),
('INAC Brass Private Limited', 'INAC1108', NOW()),
('India Forge & Drop Stampings  Ltd.', 'INDIA1109', NOW()),
('India Yamaha Motor Pvt. Ltd.', 'INDIA1110', NOW()),
('Indicators Manufacturing Company', 'INDIC1111', NOW()),
('INDIGLOBAL TRADELINKS PRIVATE LIMITED', 'INDIG1112', NOW()),
('INDO NISSIN FOODS PRIVATE LIMITED', 'INDO1113', NOW()),
('INDOPOL FOOD PROCESSING MACHINERY PVT. LTD.', 'INDOP1114', NOW()),
('INDUS SERVICES', 'INDUS1115', NOW()),
('INDUSTRIAL SALES AGENCY', 'INDUS1116', NOW()),
('Industriano Private Limited', 'INDUS1117', NOW()),
('Industrias Del Recambio India Pvt. Ltd.', 'INDUS1118', NOW()),
('Innoplix Enterprises', 'INNOP1119', NOW()),
('INNOPLIX ENTERPRISES ( Gurgaon )', 'INNOP1120', NOW()),
('INNOVETION TOOLING SOLUTION', 'INNOV1121', NOW()),
('INTERNATIONAL TRACTORS LIMITED', 'INTER1122', NOW()),
('I P INTEGRATED SERVICES PRIVATE LIMITED', 'IPI1123', NOW()),
('I P INTEGRATED SERVICES PRIVATE LTD.', 'IPI1124', NOW()),
('IP INTEGRATED SERVICES PVT. LTD. ( Rohtak )', 'IPIN1125', NOW()),
('I.P. Intergrated Service Pvt. Ltd.', 'IP1126', NOW()),
('ISGEC Heavy Engineering Limited', 'ISGEC1127', NOW()),
('IST Limited', 'ISTL1128', NOW()),
('ITC LIMITED', 'ITCL1129', NOW()),
('ITC LIMITED ( Chennai )', 'ITCL1130', NOW()),
('ITC LIMITED ( KOLKATA )', 'ITCL1131', NOW()),
('JAIN ENGINEERING WORKS', 'JAIN1132', NOW()),
('JAI PARVATI FORGE LIMITED', 'JAIP1133', NOW()),
('JAPTECH INDUSTRIES', 'JAPTE1134', NOW()),
('JAYA HIND INDUSTRIES LIMITED,', 'JAYA1135', NOW()),
('Jaycee Punching Solution Pvt Ltd', 'JAYCE1136', NOW()),
('JAYCEE PUNCHING SOLUTIONS PRIVATE LIMITED-UNIT-II', 'JAYCE1137', NOW()),
('JAY USHIN LTD', 'JAYU1138', NOW()),
('JBM AUTO LIMITED', 'JBMA1139', NOW()),
('JBM AUTO SYSTEM PVT. LTD', 'JBMA1140', NOW()),
('JBMD POLYMERS', 'JBMD1141', NOW()),
('JCB INDIA LIMITED (Assembly Unit Jaipur)', 'JCBI1142', NOW()),
('JCB INDIA LIMITED (India Part Center, Guwathi)', 'JCBI1143', NOW()),
('JCB INDIA LIMITED ( JCB BENGALURU PARTS CENTRE )', 'JCBI1144', NOW()),
('JCB India Ltd.', 'JCBI1145', NOW()),
('JCB INDIA LTD ( Kolkata Parts Centre )', 'JCBI1146', NOW()),
('JCB India LTD. (Pune)', 'JCBI1147', NOW()),
('JCB Power Products India Pvt. Ltd.', 'JCBP1148', NOW()),
('JDM BESUTO SOLUTION', 'JDMB1149', NOW()),
('JIL PACK', 'JILP1150', NOW()),
('JINDAL QUALITY TUBULAR LIMITED', 'JINDA1151', NOW()),
('Jindal Saw Limited', 'JINDA1152', NOW()),
('Jindal Stainless (Hisar) Limited', 'JINDA1153', NOW()),
('JINENDRA SALES CORPORATION', 'JINEN1154', NOW()),
('JJG AERO PRIVATE LIMITED', 'JJGA1155', NOW()),
('J J GLASTRONICS PVT LTD', 'JJG1156', NOW()),
('JMW INDIA PRIVATE LIMITED', 'JMWI1157', NOW()),
('JOHNSON MATTHEY INDIA PRIVATE LIMITED', 'JOHNS1158', NOW()),
('JOY PACK INDIA PRIVATE LIMITED', 'JOYP1159', NOW()),
('Jrew Engineering Limited', 'JREW1160', NOW()),
('JRG AUTOMOTIVE INDUSTRIES INDIA PRIVATE LIMITED', 'JRGA1161', NOW()),
('J S H PACKAGINGS', 'JSH1162', NOW()),
('JSL Stainless Ltd.', 'JSLS1163', NOW()),
('JTEKT INDIA LIMITED', 'JTEKT1164', NOW()),
('JUMPS AUTO INDUSTRIES LIMITED', 'JUMPS1165', NOW()),
('J Y AUTO PARTS', 'JYA1166', NOW()),
('KAI MANUFACTURING INDIA PVT. LTD.', 'KAIM1167', NOW()),
('KAIZEN FERRO CAST', 'KAIZE1168', NOW()),
('KALPANA FORGINGS INDIA PRIVATE LIMITED', 'KALPA1169', NOW()),
('KALYANI TECHNOFORGE LIMITED', 'KALYA1170', NOW()),
('KANAL ENTERPRISES', 'KANAL1171', NOW()),
('KANHHA CABLES PVT. LTD.', 'KANHH1172', NOW()),
('Kapil Corepacks Pvt.Ltd.', 'KAPIL1173', NOW()),
('KAPOOR  TRADING.', 'KAPOO1174', NOW()),
('KAWASAKI HEAVY INDUSTRIES (INDIA) PVT. LTD.', 'KAWAS1175', NOW()),
('KAY BOUVET ENGINEERINGS LTD.', 'KAYB1176', NOW()),
('KCL LIMITED', 'KCLL1177', NOW()),
('KCL LTD.', 'KCLL1178', NOW()),
('K.D.INTERNATIONAL', 'KDI1179', NOW()),
('KEIHIN FIE PRIVATE LIMITED', 'KEIHI1180', NOW()),
('KELKAR AUTO PARTS PRIVATE LTD.', 'KELKA1181', NOW()),
('KESAR INDUSTRIES', 'KESAR1182', NOW()),
('KHARAUJHA ENGINEERING LLP', 'KHARA1183', NOW()),
('Kheitan Enterprises', 'KHEIT1184', NOW()),
('KNORR BREMSE INDIA PVT. LTD.', 'KNORR1185', NOW()),
('Knorr-Bremse Systems for Commercial Vehicles India Private Ltd', 'KNORR1186', NOW()),
('Kobra Automotive', 'KOBRA1187', NOW()),
('Kolourmax', 'KOLOU1188', NOW()),
('KONE ELEVATOR INDIA PRIVATE LIMITED', 'KONE1189', NOW()),
('KONOIKE ASIA (INDIA) PRIVATE LIMITED', 'KONOI1190', NOW()),
('KORLOY INDIA MANUFACTURING PVT. LTD.', 'KORLO1191', NOW()),
('KQ SEATS PRIVATE LIMITED', 'KQSE1192', NOW()),
('Krishna Enterprises', 'KRISH1193', NOW()),
('KRISHNA HANGUK TECHNOLOGY PRIVATE LIMITED', 'KRISH1194', NOW()),
('KRYSTALS CABLES INDIA PRIVATE LIMITED', 'KRYST1195', NOW()),
('KSEC', 'KSEC1196', NOW()),
('K S GROUP', 'KSG1197', NOW()),
('K.S. & Sons', 'KS1198', NOW()),
('KUHME VALVES INDIA PRIVATE LIMITED', 'KUHME1199', NOW()),
('Kumaraa tools and kinives', 'KUMAR1200', NOW()),
('KUMAR PRINTERS PRIVATE LIMITED', 'KUMAR1201', NOW()),
('Kusalava International Ltd', 'KUSAL1202', NOW()),
('LAVA CAST PVT. LTD', 'LAVA1203', NOW()),
('LF LOGISTICS (INDIA) PRIVATE LIMITED', 'LFLO1204', NOW()),
('L.G.BALAKRISHNAN & BROS LIMITED', 'LGB1205', NOW()),
('LGB FORGE LIMITED', 'LGBF1206', NOW()),
('LIBRA STAMPINGS LLP', 'LIBRA1207', NOW()),
('LNM Auto Industries Private Limited', 'LNMA1208', NOW()),
('LOHIA CORP LIMITED', 'LOHIA1209', NOW()),
('LOKESH MACHINES LIMITED', 'LOKES1210', NOW()),
('LOTUS AUTO ENGINEERING LTD', 'LOTUS1211', NOW()),
('Luboil Filtration Systems Pvt. Ltd.', 'LUBOI1212', NOW()),
('Luman Industries Limited', 'LUMAN1213', NOW()),
('LUMAX AUTO TECHNOLOGIES LIMITED', 'LUMAX1214', NOW()),
('MAANVI ENTERPRISES', 'MAANV1215', NOW()),
('MAA SHANTI ENTERPRISES', 'MAAS1216', NOW()),
('Maa Sukhrala Enterprises', 'MAAS1217', NOW()),
('Macks Surface Treatments Pvt.Ltd', 'MACKS1218', NOW()),
('Madhusudan Auto Ltd.', 'MADHU1219', NOW()),
('Ma Durga Syndicate', 'MADU1220', NOW()),
('MAG FILTERS AND EQUIPMENTS PRIVATE LIMITED', 'MAGF1221', NOW()),
('Magna Powertrain Bangalore Pvt. Ltd. - MPTB - 2198', 'MAGNA1222', NOW()),
('Magneti Marelli Powertrain India Pvt. Ltd.', 'MAGNE1223', NOW()),
('MAGNUS ENTERPRISES', 'MAGNU1224', NOW()),
('MAHAVIR XPERT', 'MAHAV1225', NOW()),
('MAHINDRA AND MAHINDRA LIMITED ( Pithampur )', 'MAHIN1226', NOW()),
('MAHINDRA AND MAHINDRA LIMITED (Telangana )', 'MAHIN1227', NOW()),
('MAHINDRA AND MAHINDRA LTD. ( Bangalore )', 'MAHIN1228', NOW()),
('MAHINDRA AND MAHINDRA LTD. ( Jaipur )', 'MAHIN1229', NOW()),
('MAHINDRA AND MAHINDRA LTD. ( Kharagpur )', 'MAHIN1230', NOW()),
('MAHINDRA & MAHINDRA LIMITED ( Punjab )', 'MAHIN1231', NOW()),
('MAHINDRA & MAHINDRA LTD.', 'MAHIN1232', NOW()),
('MAHINDRA TWO WHEELERS LIMITED', 'MAHIN1233', NOW()),
('MALATI FOUNDERS PRIVATE LIMITED', 'MALAT1234', NOW()),
('Mando Automotive India Private Ltd.', 'MANDO1235', NOW()),
('MANISH AUTO INDUSTRIES', 'MANIS1236', NOW()),
('MANTHAN ENTERPRISES', 'MANTH1237', NOW()),
('Mantri Metallics  Pvt. Ltd. UNIT - 1', 'MANTR1238', NOW()),
('MARELLI POWERTRAIN INDIA PRIVATE LIMITED', 'MAREL1239', NOW()),
('MARK INDUSTRIES', 'MARK1240', NOW()),
('MARS Technologies', 'MARS1241', NOW()),
('Maruichi Kuma Steel Tube Pvt. Ltd.', 'MARUI1242', NOW()),
('MARUTHI INTERIOR WORKS', 'MARUT1243', NOW()),
('MARUTI INTERNATIONAL', 'MARUT1244', NOW()),
('Maruti Suzuki India Limited', 'MARUT1245', NOW()),
('Maruti Suzuki India Limited ( Manesar )', 'MARUT1246', NOW()),
('MARUTI SUZUKI INDIA LIMITED ( MSILME)', 'MARUT1247', NOW()),
('MAS PACKERS', 'MASP1248', NOW()),
('MASSIVE INDUSTRIES PRIVATE LIMITED', 'MASSI1249', NOW()),
('Masu International Products', 'MASU1250', NOW()),
('MECHKNOW INDIA PRIVATE LIMITED', 'MECHK1251', NOW()),
('Megha Trading Company', 'MEGHA1252', NOW()),
('Mehra Metal Components Pvt. Ltd.', 'MEHRA1253', NOW()),
('Mekins Indutries Limited', 'MEKIN1254', NOW()),
('Melstar Manufacturing Systems Private limited', 'MELST1255', NOW()),
('Merino Industries Ltd.', 'MERIN1256', NOW()),
('MERSEN INDIA PRIVATE LIMITED', 'MERSE1257', NOW()),
('Metafab Engineers (India) Pvt Ltd.', 'METAF1258', NOW()),
('METAL HANDICRAFTS SERVICE CENTRE', 'METAL1259', NOW()),
('METSO OUTOTEC INDIA PRIVATE LIMITED', 'METSO1260', NOW()),
('MICRONS INDIA', 'MICRO1261', NOW()),
('Micro Turner Pvt. Ltd.', 'MICRO1262', NOW()),
('Micro Turners Rohtak (I)', 'MICRO1263', NOW()),
('MILESTONE GEARS PRIVATE LIMITED', 'MILES1264', NOW()),
('MINDA INDUSTRIES LTD.', 'MINDA1265', NOW()),
('Minda VAST Access Systems Private Ltd.', 'MINDA1266', NOW()),
('Mita India Pvt. Ltd.', 'MITA1267', NOW()),
('Mitsubishi Electric Automotive India (P) Ltd.', 'MITSU1268', NOW()),
('MKG ENGINEERS', 'MKGE1269', NOW()),
('ML SPRINGS INDIA PRIVATE LIMITED', 'MLSP1270', NOW()),
('MM AUTO INDUSTRIES LIMITED', 'MMAU1271', NOW()),
('MNS LOGISTICS PVT. LTD.', 'MNSL1272', NOW()),
('MOD AUTOMOBILES PRIVATE LIMITED', 'MODA1273', NOW()),
('MOD SERAP INDUSTRIES', 'MODS1274', NOW()),
('MOGLI LABS (INDIA) P LTD.', 'MOGLI1275', NOW()),
('MOGLI LABS (INDIA) PRIVATE LIMITED', 'MOGLI1276', NOW()),
('Mogli Labs (India) Private Limited ( Karnataka )', 'MOGLI1277', NOW()),
('Mohindra Fasteners Ltd.', 'MOHIN1278', NOW()),
('Motherson Moulds and Diecasting Limited', 'MOTHE1279', NOW()),
('MOTHERSON SUMI SYSTEMS LTD', 'MOTHE1280', NOW()),
('M/S ARCHANA  ENTERPRISES', 'MSA1281', NOW()),
('M/S BALA JI MILK EQUIPMENTS', 'MSB1282', NOW()),
('M/S CHAMUNDI DIE CAST (P) LTD', 'MSC1283', NOW()),
('M/S KARAN INDUSTRY', 'MSK1284', NOW()),
('M/S MAWANIYA AUTOMATS', 'MSM1285', NOW()),
('M/S M J ENTERPRISE', 'MSM1286', NOW()),
('M/s. Paramount Surgimed Ltd.', 'MS1287', NOW()),
('M/S PUROLITE INDUSTRIES', 'MSP1288', NOW()),
('M/S SHARMA WOODEN PACKERS', 'MSS1289', NOW()),
('Mukul Sales', 'MUKUL1290', NOW()),
('MUKUL SALES''', 'MUKUL1291', NOW()),
('Multitec Industries', 'MULTI1292', NOW()),
('MULTIVAC LARAON INDIA PVT. LTD.', 'MULTI1293', NOW()),
('Munjal Kiriu Industries (P) Ltd.', 'MUNJA1294', NOW()),
('MUSKAN PACKAGING PVT.LTD.', 'MUSKA1295', NOW()),
('NAGATA INDIA PVT. LTD.', 'NAGAT1296', NOW()),
('NAMOH TOOLINGS', 'NAMOH1297', NOW()),
('Napino Auto & Electronics Ltd', 'NAPIN1298', NOW()),
('NASH INDUSTRIES (I) PRIVATE LIMITED', 'NASH1299', NOW()),
('NATIONAL ENGINEERING INDUSTRIES LTD.', 'NATIO1300', NOW()),
('N.B.G. Printographic Machinery Co. Pvt. Ltd.', 'NBG1301', NOW()),
('NEOLITE ZKW LIGHTINGS PVT. LTD.', 'NEOLI1302', NOW()),
('NEOPERL INDIA PVT.LTD.', 'NEOPE1303', NOW()),
('Neosym Industry Limited', 'NEOSY1304', NOW()),
('NEW LIGHT PRODUCTS ( S )', 'NEWL1305', NOW()),
('NEW RANDHIR PRESS TOOLS', 'NEWR1306', NOW()),
('NEW SALES CORPORATION ( S )', 'NEWS1307', NOW()),
('Nexteer Automotive India Private Limited', 'NEXTE1308', NOW()),
('NHK SPRING INDIA LTD.', 'NHKS1309', NOW()),
('NIPPON LEAKLESS TALBROS PRIVATE LTD.', 'NIPPO1310', NOW()),
('Nippon Oil Pump India Private Limited.', 'NIPPO1311', NOW()),
('Nippon Steel & Sumikin Pipe India PVT Ltd.', 'NIPPO1312', NOW()),
('NIRVANA INDIA PRIVATE LIMITED', 'NIRVA1313', NOW()),
('Nissan Motor India Pvt Limited', 'NISSA1314', NOW()),
('NNR Global Logistics India Pvt. Ltd.', 'NNRG1315', NOW()),
('N.P. ENTERPRISES', 'NP1316', NOW()),
('N S LOGISTICS SERVICE', 'NSL1317', NOW()),
('NTF India Pvt. Ltd.', 'NTFI1318', NOW()),
('OCAP CHASSIS PARTS PVT. LTD.', 'OCAP1319', NOW()),
('OCL IRON AND STEEL LTD.', 'OCLI1320', NOW()),
('OCTAPACK', 'OCTAP1321', NOW()),
('OJAS ENTERPRISES', 'OJAS1322', NOW()),
('OKAYA EV PRIVATE LIMITED', 'OKAYA1323', NOW()),
('OMKAR ENTERPRISES', 'OMKAR1324', NOW()),
('OM PACKAGING SOLUTION', 'OMPA1325', NOW()),
('OMP INDIA PRIVATE LIMITED', 'OMPI1326', NOW()),
('OM Sai Nath Packing Solutions', 'OMSA1327', NOW()),
('Om Sai Packers', 'OMSA1328', NOW()),
('ONE PACK SOLUTIONS', 'ONEP1329', NOW()),
('OPHTECHNICS UNLIMITED', 'OPHTE1330', NOW()),
('ORIENT MARINE LINES', 'ORIEN1331', NOW()),
('Orthocure Healthcare Private Limited', 'ORTHO1332', NOW()),
('PADMINI VNA MECHATRONICS LIMITED', 'PADMI1333', NOW()),
('PADMINI VNA MECHATRONICS PVT. LTD.', 'PADMI1334', NOW()),
('Pahadi Goodness Pvt. Ltd.', 'PAHAD1335', NOW()),
('PAL SHELLCAST PRIVATE LIMITED', 'PALS1336', NOW()),
('Parthas Engineering', 'PARTH1337', NOW()),
('PCI Precision Casting Ltd.', 'PCIP1338', NOW()),
('Pearl Engineering Co.', 'PEARL1339', NOW()),
('PEARL ENGINEERING CO. ( GOA )', 'PEARL1340', NOW()),
('PERFECT TOOLING SOLUTIONS', 'PERFE1341', NOW()),
('PERSISTENT GLOBAL LOGISTICS LLP', 'PERSI1342', NOW()),
('PES HYDRAULICS (INDIA) PVT. LTD.', 'PESH1343', NOW()),
('PIAGGIO VEHICLES PRIVATE LIMITED', 'PIAGG1344', NOW()),
('PLR SYSTEMS PRIVATE LIMITED', 'PLRS1345', NOW()),
('POCLAIN HYDRAULICS PVT. LTD.', 'POCLA1346', NOW()),
('POSSIBLE POLYMER INDUSTRIES', 'POSSI1347', NOW()),
('PRAKRITI INDUSTRIES', 'PRAKR1348', NOW()),
('PRAYAG INDUSTRIES', 'PRAYA1349', NOW()),
('PREBO AUTOMOTIVE PRIVATE LIMITED', 'PREBO1350', NOW()),
('PRECISION EXPORTS', 'PRECI1351', NOW()),
('PRECISION KALPURJA UDYOG PVT. LTD.', 'PRECI1352', NOW()),
('PREET SPARES PVT. LTD.', 'PREET1353', NOW()),
('PREET TRACTORS PVT. LTD.', 'PREET1354', NOW()),
('PREM BROTHER INTERNATIONAL PRIVATE LIMITED', 'PREM1355', NOW()),
('PREMIER PLASMOTEC PRIVATE LIMITED', 'PREMI1356', NOW()),
('PREMIUM PLAST LIMITED', 'PREMI1357', NOW()),
('PRIME INC', 'PRIME1358', NOW()),
('PRITIKA INDUSTRIES LTD.', 'PRITI1359', NOW()),
('Prompt Packaging & logistics', 'PROMP1360', NOW()),
('PROMPT PACKWAYS', 'PROMP1361', NOW()),
('Pronk Multiservice India Private Limited', 'PRONK1362', NOW()),
('PRONK MULTISERVICE INDIA PRIVATE LTD.', 'PRONK1363', NOW()),
('Pronk Multiservice India Pvt. Ltd.', 'PRONK1364', NOW()),
('Pronk Multiservice India Pvt Ltd 2013-14', 'PRONK1365', NOW()),
('PROPACK ENTERPRISES', 'PROPA1366', NOW()),
('P S  Packing Solution', 'PS1367', NOW()),
('Punjab Engineering Works(Jaipur South)', 'PUNJA1368', NOW()),
('PUNJ LLOYD RAKSHA SYSTEMS PVT. LTD.', 'PUNJ1369', NOW()),
('PUSHP ENTERPRISES', 'PUSHP1370', NOW()),
('PV CLEAN MOBILITY TECHNOLOGIES PRIVATE LIMITED', 'PVCL1371', NOW()),
('P V INDUSTRIAL SOLUTIONS', 'PVI1372', NOW()),
('Q2 CONNECTICS PRIVATE LIMITED', 'Q2CO1373', NOW()),
('QH Talbros Limited', 'QHTA1374', NOW()),
('QH TALBROS PRIVATE LIMITED', 'QHTA1375', NOW()),
('QH Talbros Pvt. Ltd.', 'QHTA1376', NOW()),
('RACHIT ENTERPRISES', 'RACHI1377', NOW()),
('Radish Technologies', 'RADIS1378', NOW()),
('RAHUL TRADING COMPANY', 'RAHUL1379', NOW()),
('RAICAM AUTOMOTIVE PRIVATE LIMITED', 'RAICA1380', NOW()),
('Rajhans Metals Private Limited Unit II', 'RAJHA1381', NOW()),
('Raj Kamal Traderds', 'RAJK1382', NOW()),
('Rajshree Automation and CNC Services', 'RAJSH1383', NOW()),
('RANDOM ENGINEERING', 'RANDO1384', NOW()),
('RANE MADRAS LIMITED', 'RANE1385', NOW()),
('RANE (MADRAS) LTD.', 'RANE1386', NOW()),
('RANE NSK STEERING SYSTEMS PVT. LIMITED', 'RANE1387', NOW()),
('RANE NSK STEERING SYSTEMS PVT. LTD. ( Bawal )', 'RANE1388', NOW()),
('RANJANA GOYAL', 'RANJA1389', NOW()),
('RAPACKIN WOODS PRIVATE LIMITED', 'RAPAC1390', NOW()),
('RASAII FLOW LINES PRIVATE LIMITED', 'RASAI1391', NOW()),
('RATAN INDUSTRIES PVT LTD.', 'RATAN1392', NOW()),
('RAY International', 'RAYI1393', NOW()),
('RD PRINTERS AND PACKERS', 'RDPR1394', NOW()),
('RECAUTO INDIA PVT LTD', 'RECAU1395', NOW()),
('RELIABLE AUTOTECH PVT LTD', 'RELIA1396', NOW()),
('Renault India Private Limited', 'RENAU1397', NOW()),
('Renault India Private Ltd.', 'RENAU1398', NOW()),
('Renault Nissan Automotive India Pvt Ltd', 'RENAU1399', NOW()),
('RENEE COSMETICS PRIVATE LIMITED', 'RENEE1400', NOW()),
('RESEARCH DEVELOPMENT AND MANUFACTURING CORPORATION', 'RESEA1401', NOW()),
('REVENT PRECISION ENGINEERING LIMITED', 'REVEN1402', NOW()),
('RICO FLUIDTRONICS LIMITED', 'RICO1403', NOW()),
('Riello PCI India Pvt. Ltd.', 'RIELL1404', NOW()),
('Riello Power India Pvt. Ltd.', 'RIELL1405', NOW()),
('RING PLUS AQUA LTD', 'RING1406', NOW()),
('RISEN SOURCING', 'RISEN1407', NOW()),
('RISHI CAR RENTALS PVT LTD', 'RISHI1408', NOW()),
('R M COMPONENTS PVT LTD.', 'RMC1409', NOW()),
('ROCKPECKER PRIVATE LIMITED', 'ROCKP1410', NOW()),
('Rohit Polymer Industries', 'ROHIT1411', NOW()),
('ROOP AUTOMOTIVES LIMITED', 'ROOP1412', NOW()),
('ROOTS CAST PRIVATE LTD.', 'ROOTS1413', NOW()),
('ROTOMAC INDUSTRIES  PVT. LTD.', 'ROTOM1414', NOW()),
('ROYAL COMPOSITES PRIVATE LIMITED', 'ROYAL1415', NOW()),
('RP LASERTECH PVT. LTD.', 'RPLA1416', NOW()),
('RSB Transmissions(I) Ltd', 'RSBT1417', NOW()),
('R.S.Industries', 'RSI1418', NOW()),
('SADHU AUTO PARTS Pvt Ltd.', 'SADHU1419', NOW()),
('SAFECON INDIA TECHNOLOGIES PRIVATE LIMITED', 'SAFEC1420', NOW()),
('SAINA PRINT & PACK SOLUTIONS', 'SAINA1421', NOW()),
('Sai Packaging', 'SAIP1422', NOW()),
('SAI PACKAGING SOLUTIONS', 'SAIP1423', NOW()),
('Sampark India Logistics Private Ltd', 'SAMPA1424', NOW()),
('SAMSUNG INDIA ELECTRONICS PRIVATE LIMITED', 'SAMSU1425', NOW()),
('SAMSUNG IREX INDIA LLP', 'SAMSU1426', NOW()),
('SAMVARDHANA MOTHERSON GLOBAL CARRIERS LIMITED', 'SAMVA1427', NOW()),
('Samvardhana Motherson International Limited', 'SAMVA1428', NOW()),
('Sanko Svance JRG Tooling India Pvt. Ltd', 'SANKO1429', NOW()),
('SANOH INDIA PRIVATE LIMITED', 'SANOH1430', NOW()),
('SANPACK', 'SANPA1431', NOW()),
('SANSERA ENGINEERING LIMITED', 'SANSE1432', NOW()),
('SANSERA ENGINEERING LTD.', 'SANSE1433', NOW()),
('SANSKAAR ASSOCIATES', 'SANSK1434', NOW()),
('Santec Exim Private Limited', 'SANTE1435', NOW()),
('Santech Enterprises', 'SANTE1436', NOW()),
('SATELITE FORGING PRIVATE LIMITED', 'SATEL1437', NOW()),
('SATYAM PACKAGING', 'SATYA1438', NOW()),
('Saurer Textile Solutions Private Limited', 'SAURE1439', NOW()),
('SAXON FLUID SEALING DEVICES', 'SAXON1440', NOW()),
('SBN MANUFACTURING CO.', 'SBNM1441', NOW()),
('SCHENCK PROCESS INDIA PRIVATE LIMITED', 'SCHEN1442', NOW()),
('S.D. AUTO ENGINEERING WORKS PVT. LTD.', 'SD1443', NOW()),
('SEBROS INDUSTRIES PRIVATE LIMITED UNIT I', 'SEBRO1444', NOW()),
('SEHGAL CONSULTANTS PVT. LTD.', 'SEHGA1445', NOW()),
('SEIGA INTERNATIONAL PRIVATE LIMITED', 'SEIGA1446', NOW()),
('Setco Automotive Ltd.', 'SETCO1447', NOW()),
('Setco Automotive Ltd. ( Guj. )', 'SETCO1448', NOW()),
('SETCO AUTO SYSTEMS PRIVATE LIMITED', 'SETCO1449', NOW()),
('SETCO AUTO SYSTEMS PRIVATE LIMITED ( Gujrat )', 'SETCO1450', NOW()),
('SHARP ENGINEERS', 'SHARP1451', NOW()),
('SHIVAM AUTOTECH LIMITED', 'SHIVA1452', NOW()),
('SHIVANI LOCKS PRIVATE LIMITED (UNIT-I)', 'SHIVA1453', NOW()),
('SHIVA TECHNIQUES SURFACES PVT. LTD.', 'SHIVA1454', NOW()),
('SHIVAY MOTOR CO', 'SHIVA1455', NOW()),
('SHIV SHAKTI INDUSTRIES', 'SHIV1456', NOW()),
('SHOWA-ARCH METAL PRIVATE LIMITED', 'SHOWA1457', NOW()),
('SHOWA DENKO MATERIALS (INDIA) PVT. LTD.', 'SHOWA1458', NOW()),
('Shree Bhiksu Packaging Pvt. Ltd.', 'SHREE1459', NOW()),
('SHREE GANESH ENGINEERING SOLUTIONS', 'SHREE1460', NOW()),
('SHREE GANESH PACKAGING PRODUCTS', 'SHREE1461', NOW()),
('SHREE RAM PACKAGING INDUSTRIES (S)', 'SHREE1462', NOW()),
('SHREE RAM RAJA WOOD PACKERS', 'SHREE1463', NOW()),
('Shresty India', 'SHRES1464', NOW()),
('Shri Hanumant Kripa Tranding Company', 'SHRI1465', NOW()),
('SHRI KRISHNA FORGINGS', 'SHRI1466', NOW()),
('Shrinivas Engineering Autocomponents Pvt. Ltd', 'SHRIN1467', NOW()),
('SHRI RAM AUTOTECH PRIVATE LIMITED', 'SHRI1468', NOW()),
('SHRI RAM ENGINEERS', 'SHRI1469', NOW()),
('Shri Shyam Polymer Industries', 'SHRI1470', NOW()),
('SHRI SHYAM POLYMER INDUSTRIES''', 'SHRI1471', NOW()),
('Shyama Engineering', 'SHYAM1472', NOW()),
('Siddharth Grease & Lubes Pvt. Ltd.', 'SIDDH1473', NOW()),
('SIDHARTH EXPORTS', 'SIDHA1474', NOW()),
('SIDHARTH INDUSTRIES', 'SIDHA1475', NOW()),
('Siemens Healthcare Pvt. Ltd.', 'SIEME1476', NOW()),
('SIEMENS LIMITED', 'SIEME1477', NOW()),
('SIEMENS LIMITED ( Delhi )', 'SIEME1478', NOW()),
('SIEMENS LIMITED ( Madhya Pradesh )', 'SIEME1479', NOW()),
('Siemens Ltd.', 'SIEME1480', NOW()),
('SIGMA AUTOMOTIVE MATERIALS PVT. LTD.', 'SIGMA1481', NOW()),
('SIGMA CORPORATION INDIA LIMITED', 'SIGMA1482', NOW()),
('SIGMA ELECTRIC MANUFACTURING CORPORATION PRIVATE LTD.', 'SIGMA1483', NOW()),
('SIGMA ELECTRIC MANUFACTURING CORPORATION PVT. LTD.', 'SIGMA1484', NOW()),
('Sigma Electric Manufacturing Corp. Pvt. Ltd.', 'SIGMA1485', NOW()),
('SIGMA MOULDS & STAMPINGS Pvt.Ltd', 'SIGMA1486', NOW()),
('SIGNODE INDIA LIMITED', 'SIGNO1487', NOW()),
('SIGNODE INDIA LIMITED ( PITHAMPUR )', 'SIGNO1488', NOW()),
('SILICON CORTECH PVT. LTD.', 'SILIC1489', NOW()),
('SIMPLI FIER', 'SIMPL1490', NOW()),
('SINGHANIA INTERNATIONAL LTD.', 'SINGH1491', NOW()),
('SINGLA FORGING PRIVATE LIMITED', 'SINGL1492', NOW()),
('SINTERCOM INDIA LIMITED', 'SINTE1493', NOW()),
('S K Auto India', 'SKA1494', NOW()),
('SKF TECHNOLOGIES INDIA PRIVATE LIMITED', 'SKFT1495', NOW()),
('SKN INDUSTRIES', 'SKNI1496', NOW()),
('SKODA AUTO VOLKSWAGEN INDIA PRIVATE LIMITED', 'SKODA1497', NOW()),
('S.K.PACKAGING (S)', 'SKP1498', NOW()),
('SK SYSTEMS PVT.LTD.', 'SKSY1499', NOW()),
('SKYBLUE CHEMICALS', 'SKYBL1500', NOW()),
('SKYTECH ENGINEERING', 'SKYTE1501', NOW()),
('SMART CONTROLS INDIA LIMITED', 'SMART1502', NOW()),
('S.M ENTERPRISES', 'SME1503', NOW()),
('SMITH INDUSTRIAL CORPORATION PRIVATE LIMITED', 'SMITH1504', NOW()),
('S N TOOLING SOLUTION', 'SNT1505', NOW()),
('Socomec India Private Limited', 'SOCOM1506', NOW()),
('SOGEFI ENGINE SYSTEMS INDIA PVT. LTD.', 'SOGEF1507', NOW()),
('SONA BLW PRECISION FORGINGS LTD.', 'SONA1508', NOW()),
('Sona Koyo Steering Systems Ltd.', 'SONA1509', NOW()),
('SONIA FORGINGS PVT. LTD.', 'SONIA1510', NOW()),
('S.P.INDUSTRIES', 'SPI1511', NOW()),
('SPIRE INDIA', 'SPIRE1512', NOW()),
('SR Enterprises', 'SREN1513', NOW()),
('SRI LAXMI PACKERS', 'SRIL1514', NOW()),
('SRI SAI TRADING CO.', 'SRIS1515', NOW()),
('Sri Triveni Crafts', 'SRIT1516', NOW()),
('SRK TELE ENERGY INDIA PVT. LTD.', 'SRKT1517', NOW()),
('SRN ENTERPRISES', 'SRNE1518', NOW()),
('STANDARD SINTERED PRODUCTS PVT LTD', 'STAND1519', NOW()),
('STAR SINTERED PRODUCTS LIMITED', 'STAR1520', NOW()),
('STC India', 'STCI1521', NOW()),
('STEAG Energy Services ( INDIA ) Pvt. Ltd.', 'STEAG1522', NOW()),
('STEELBIRD INTERNATIONAL', 'STEEL1523', NOW()),
('Stork Rubber Products Pvt. Ltd.', 'STORK1524', NOW()),
('SUNBEAM AUTO PVT LTD (Rj)', 'SUNBE1525', NOW()),
('SUNBEAM LIGHTWEIGHTING SOLUTIONS PVT. LTD.', 'SUNBE1526', NOW()),
('SUNBEAM LIGHTWEIGHTING SOLUTIONS PVT. LTD. (PUNJAB)', 'SUNBE1527', NOW()),
('SUNCITY HEIGHTS RESIDENTS  WELFARE ASSOCIATION', 'SUNCI1528', NOW()),
('SUNDRAM FASTENERS LIMITED', 'SUNDR1529', NOW()),
('SUNEEL AUTO COMP. PVT.LTD.', 'SUNEE1530', NOW()),
('SUNLORD INTERNATIONAL', 'SUNLO1531', NOW()),
('SUNRISE PACKAGING INDUSTRIES', 'SUNRI1532', NOW()),
('SUN SHINE PACKAGING INDUSTRIES', 'SUNS1533', NOW()),
('Suprajit Engineering Ltd', 'SUPRA1534', NOW()),
('Supreme Automech (India) Pvt. Ltd', 'SUPRE1535', NOW()),
('SUREKSHA  ENTERPRISES', 'SUREK1536', NOW()),
('SURI AUTO PVT. LTD.', 'SURI1537', NOW()),
('Suruga India Pvt. Ltd.', 'SURUG1538', NOW()),
('Suzuki Motorcycle India Pvt.Ltd.', 'SUZUK1539', NOW()),
('SUZUKI MOTOR GUJARAT PRIVATE LIMITED', 'SUZUK1540', NOW()),
('Swai Auto Transmission System', 'SWAI1541', NOW()),
('Swan Aluminiums Pvt.Ltd.', 'SWAN1542', NOW()),
('SWARAJ ENGINES LTD.', 'SWARA1543', NOW()),
('SWISSH TECHNOLOGIES', 'SWISS1544', NOW()),
('SYNDICATE WIPER SYSTEMS PVT. LTD.', 'SYNDI1545', NOW()),
('SYSCON INSTRUMENTS PRIVATE LIMITED', 'SYSCO1546', NOW()),
('TALBROS AUTOMOTIVE COMPONENTS LTD.', 'TALBR1547', NOW()),
('TALBROS AUTOMOTIVE COMPONENTS LTD. ( Pune )', 'TALBR1548', NOW()),
('Talbros Engineering Ltd.', 'TALBR1549', NOW()),
('TALBROS MARUGO RUBBER PVT. LTD.', 'TALBR1550', NOW()),
('TASA MICRO SPECIAL PURPOSE MACHINE PVT. LTD.', 'TASA1551', NOW()),
('TATA FICOSA AUTOMOTIVE SYSTEMS LIMITED', 'TATA1552', NOW()),
('TATA MOTORS LIMITED', 'TATA1553', NOW()),
('Techno Sales', 'TECHN1554', NOW()),
('TECNOVOS PACKS', 'TECNO1555', NOW()),
('TECNOVOS PACKS ( FARIDABAD )', 'TECNO1556', NOW()),
('TECQUA CONSULTING SERVICES', 'TECQU1557', NOW()),
('TELMAT MATERIAL & TECHNOLOGIES INDIA PVT. LTD.', 'TELMA1558', NOW()),
('TE Thermo Electric Company India Pvt. Ltd', 'TETH1559', NOW()),
('TEXSPIN BEARINGS LTD', 'TEXSP1560', NOW()),
('THE HI-TECH Engineering Systems Pvt. Ltd.', 'THEH1561', NOW()),
('THE HI-TECH GEARS LTD. PLANT-III', 'THEH1562', NOW()),
('The Professional Packer Movers', 'THEP1563', NOW()),
('THREESIXTY PACKAGING PVT. LTD.', 'THREE1564', NOW()),
('Tightwell Fasteners', 'TIGHT1565', NOW()),
('TN PACKAGING PVT. LTD.', 'TNPA1566', NOW()),
('TOKAI RUBBER AUTO-PARTS INDIA PRIVATE LIMITED', 'TOKAI1567', NOW()),
('Toll (India) Logistics Pvt. Ltd.', 'TOLL1568', NOW()),
('TONGLIT AUTOGISTIC PRIVATE LIMITED', 'TONGL1569', NOW()),
('TONGLIT AUTOGISTIC PRIVATE LTD.', 'TONGL1570', NOW()),
('TONGLIT AUTOGISTIC PVT. LTD.', 'TONGL1571', NOW()),
('TORESO LLP', 'TORES1572', NOW()),
('TOSEI ENGINEERING PRIVATE LIMITED', 'TOSEI1573', NOW()),
('TOTAL INDUSTRIAL SOLUTION', 'TOTAL1574', NOW()),
('Total Pack', 'TOTAL1575', NOW()),
('Toyota Tsusho India Pvt. Ltd.', 'TOYOT1576', NOW()),
('TRACK COMPONENTS LTD', 'TRACK1577', NOW()),
('TRADEIMPEX POLYMERS (INDIA) PRIVATE LIMITED', 'TRADE1578', NOW()),
('TRAFAG CONTROLS INDIA PVT LTD.', 'TRAFA1579', NOW()),
('TRANSHEALTH (P) LTD.', 'TRANS1580', NOW()),
('Trans Technology India Pvt Ltd', 'TRANS1581', NOW()),
('T R Engineers Pvt Ltd', 'TRE1582', NOW()),
('TRICOLITE ELECTRICAL INDUSTRIES LIMITED', 'TRICO1583', NOW()),
('TRIKUTA METALS', 'TRIKU1584', NOW()),
('TRINA NRE TRANSPORTATION LTD', 'TRINA1585', NOW()),
('T S PLASTIC', 'TSP1586', NOW()),
('TTGA PRIVATE LIMITED', 'TTGA1587', NOW()),
('TURNING POINT', 'TURNI1588', NOW()),
('UMIYA PACKAGING', 'UMIYA1589', NOW()),
('Unique Technology & Services', 'UNIQU1590', NOW()),
('Unitech Industrial Solutions', 'UNITE1591', NOW()),
('USHA AMORPHOUS METALS PRIVATE LIMITED', 'USHA1592', NOW()),
('VACHI EXPORTS PRIVATE LIMITED', 'VACHI1593', NOW()),
('VALEO INDIA PRIVATE LIMITED', 'VALEO1594', NOW()),
('VALEO INDIA PRIVATE LTD.', 'VALEO1595', NOW()),
('Valeo India Pvt Ltd (Electrical Systems)', 'VALEO1596', NOW()),
('Vanshika Enterprises', 'VANSH1597', NOW()),
('VE COMMERCIAL VEHICLES LIMITED', 'VECO1598', NOW()),
('VE COMMERCIAL VEHICLES LIMITED''', 'VECO1599', NOW()),
('VE COMMERCIAL VEHICLES LIMITED ( Bangalore )', 'VECO1600', NOW()),
('VE COMMERCIAL VEHICLES LIMITED (UNIT- VEPT )', 'VECO1601', NOW()),
('VE Commercial Vehicles Ltd.', 'VECO1602', NOW()),
('VE COMMERCIAL VEHICLES LTD.''', 'VECO1603', NOW()),
('VE COMMERCIAL VEHICLES LTD. ( RDC )', 'VECO1604', NOW()),
('VED ENTERPRISES', 'VEDE1605', NOW()),
('VEEMAP TECHNOLOGIES PRIVATE LIMITED', 'VEEMA1606', NOW()),
('Viat Instruments Pvt.Ltd.', 'VIAT1607', NOW()),
('Vidhi International', 'VIDHI1608', NOW()),
('Vijay Packing Co.', 'VIJAY1609', NOW()),
('VIKAS EXPORTS', 'VIKAS1610', NOW()),
('VIRAL ENGINEERS', 'VIRAL1611', NOW()),
('VIRAL ENTERPRISE', 'VIRAL1612', NOW()),
('VIRGO OVERSEAS', 'VIRGO1613', NOW()),
('VISHNU ASSOCIATES INDIA PRIVATE LIMITED', 'VISHN1614', NOW()),
('VISHWAKARMA SAW MILL', 'VISHW1615', NOW()),
('VIVEK PETRO CHEMICALS', 'VIVEK1616', NOW()),
('VMAP Technologies', 'VMAP1617', NOW()),
('V. M. INDUSTRIES', 'VM1618', NOW()),
('V R PACKAGING SOLUTIONS', 'VRP1619', NOW()),
('VSS GROUP INDIA', 'VSSG1620', NOW()),
('V TECH AUTOMATION', 'VTEC1621', NOW()),
('VTS TF AIR SYSTEMS PVT LTD', 'VTST1622', NOW()),
('WAHI SONS PRIVATE LIMITED', 'WAHI1623', NOW()),
('Well Tech Packaging', 'WELL1624', NOW()),
('WESTERN HEAT AND FORGE PVT.LTD.', 'WESTE1625', NOW()),
('WOCO TECH ELASTOMERE NOIDA LIMITED', 'WOCO1626', NOW()),
('WOODFIELD SYSTEMS INTERNATIONAL PRIVATE LIMITED', 'WOODF1627', NOW()),
('XLP ENGINEERS PVT. LTD.', 'XLPE1628', NOW()),
('Yakal Computers & Refill Technologies', 'YAKAL1629', NOW()),
('Yamazen Machinery and tools India Pvt Ltd.', 'YAMAZ1630', NOW()),
('Yuantai International Supply Chain Management Pvt. Ltd.', 'YUANT1631', NOW()),
('Yusen Logistics (India) Pvt Limited', 'YUSEN1632', NOW())
ON CONFLICT (name) DO NOTHING;
